import test from 'node:test';import assert from 'node:assert/strict';import {id,hash} from '../../src/core.mjs';
import {membership,documentScope,evidenceGrant,holdEvidence,reassignTask,reassignSource,reassignAction,preferences,markRead,requestOcr} from '../../src/operations/management.mjs';
import {requestExport,reviewExport,encodeInventory,downloadExport,publicExport} from '../../src/operations/exports.mjs';
import {dueReminder} from '../../src/operations/reminders.mjs';import {fixture} from './memory.mjs';
const why='Transferred after an approved staff responsibility change.',denied=(fn,code)=>assert.rejects(fn,e=>e.code===code);
async function setupTask(f,extras={}){return f.s.insert('u_tasks',{period_id:f.period,campus_id:f.campus,kpi_id:id(),assignee_id:f.actors.ENTRY.id,reviewer_id:f.actors.REVIEWER.id,status:'OPEN',...extras});}
async function source(f){return f.s.insert('u_c_sources',{name:'Synthetic DG',code:'DG_TEST',period_id:f.period,campus_id:f.campus,owner_id:f.actors.ENTRY.id,ownership_version:1,kind:'STATIONARY_DIESEL',unit:'litre'});}
test('department membership and scope permit a formerly denied document',async()=>{const f=fixture(),dep=await f.s.insert('u_departments',{campus_id:f.campus,name:'Hostels',code:'HOSTELS'}),entry=f.s.for(f.actors.OTHER_ENTRY);await denied(()=>entry.get('documents',f.document.id),'NOT_FOUND');await membership(f.s,{version:0,userId:entry.user.id,campusId:f.campus,departmentId:dep.id,active:true,reason:why});await documentScope(f.s,f.document.id,{version:0,visibility:'DEPARTMENT',campusId:f.campus,departmentId:dep.id,reason:why});assert.equal((await entry.get('documents',f.document.id)).id,f.document.id);});
test('membership revocation immediately denies document metadata in a new request',async()=>{const f=fixture(),entry=f.s.for(f.actors.OTHER_ENTRY),body={version:0,userId:entry.user.id,campusId:f.campus,active:true,reason:why};const m=await membership(f.s,body);await documentScope(f.s,f.document.id,{version:0,visibility:'CAMPUS',campusId:f.campus,reason:why});assert.ok(await entry.get('documents',f.document.id));await membership(f.s,{...body,id:m.id,version:m.version,active:false});await denied(()=>entry.get('documents',f.document.id),'NOT_FOUND');});
test('membership cannot silently change user/campus identity',async()=>{const f=fixture(),m=await membership(f.s,{userId:f.actors.ENTRY.id,campusId:f.campus,active:true,reason:why});await denied(()=>membership(f.s,{id:m.id,version:1,userId:f.actors.OTHER_ENTRY.id,campusId:f.campus,active:true,reason:why}),'IMMUTABLE_SCOPE');});
test('department campus mismatch and inactive assignee rejected',async()=>{const f=fixture(),dep=await f.s.insert('u_departments',{campus_id:id(),name:'Other'});await denied(()=>membership(f.s,{userId:f.actors.ENTRY.id,campusId:f.campus,departmentId:dep.id,active:true,reason:why}),'DEPARTMENT_CAMPUS');f.state.tables.users.find(u=>u.id===f.actors.ENTRY.id).active=false;await denied(()=>membership(f.s,{userId:f.actors.ENTRY.id,campusId:f.campus,active:true,reason:why}),'INVALID_ASSIGNEE');});
for(const role of ['ENTRY','REVIEWER','LEADERSHIP'])test(role+' cannot administer memberships or document grants',async()=>{const f=fixture(),s=f.s.for(f.actors[role]);await denied(()=>membership(s,{}),'FORBIDDEN');await denied(()=>evidenceGrant(s,f.document.id,{}),'FORBIDDEN');await denied(()=>holdEvidence(s,f.document.id,{}),'FORBIDDEN');});
test('grant/revoke checks current version and raw original never changes',async()=>{const f=fixture(),body={version:0,userId:f.actors.OTHER_ENTRY.id,active:true,reason:why},original=structuredClone(f.state.tables.documents);const g=await evidenceGrant(f.s,f.document.id,body);assert.ok(await f.s.for(f.actors.OTHER_ENTRY).get('documents',f.document.id));await denied(()=>evidenceGrant(f.s,f.document.id,{...body,active:false}),'STALE_VERSION');await evidenceGrant(f.s,f.document.id,{...body,version:g.version,active:false});await denied(()=>f.s.for(f.actors.OTHER_ENTRY).get('documents',f.document.id),'NOT_FOUND');assert.deepEqual(f.state.tables.documents,original);});
test('private scope cannot carry sharing identifiers and no silent stale mutation',async()=>{const f=fixture();await denied(()=>documentScope(f.s,f.document.id,{version:0,visibility:'PRIVATE',campusId:f.campus,reason:why}),'INVALID_SCOPE');const r=await documentScope(f.s,f.document.id,{version:0,visibility:'PRIVATE',reason:why});await denied(()=>documentScope(f.s,f.document.id,{version:0,visibility:'CAMPUS',campusId:f.campus,reason:why}),'STALE_VERSION');assert.equal(r.version,1);});
test('indefinite preservation hold and explicit release are audited; no delete',async()=>{const f=fixture();const r=await holdEvidence(f.s,f.document.id,{version:0,hold:true,reason:why});assert.equal(r.hold_reason,why);assert.equal(r.hold_until,null);const released=await holdEvidence(f.s,f.document.id,{version:r.version,hold:false,reason:'Release approved after internal retention review.'});assert.equal(released.hold_reason,null);assert.equal(f.state.tables.documents.length,1);assert.equal(f.state.audit.at(-1).action,'O_EVIDENCE_HOLD_RELEASED');});
test('past and invalid retention dates rejected',async()=>{const f=fixture();for(const until of ['invalid','2000-01-01T00:00:00Z'])await denied(()=>holdEvidence(f.s,f.document.id,{version:0,hold:true,until,reason:why}),'INVALID_DATE');});
test('task transfer retains authorship, returns pending rows and records before/after',async()=>{const f=fixture(),t=await setupTask(f),draft=await f.s.insert('u_submissions',{task_id:t.id,status:'SUBMITTED',created_by:f.actors.ENTRY.id,value:'100',revision:1});const b={version:t.version,assigneeId:f.actors.OTHER_ENTRY.id,reviewerId:f.actors.REVIEWER.id,reason:why};await denied(()=>reassignTask(f.s,t.id,b),'PENDING_SUBMISSIONS');const r=await reassignTask(f.s,t.id,{...b,returnPending:true});assert.equal(r.assignee_id,f.actors.OTHER_ENTRY.id);const returned=await f.s.get('u_submissions',draft.id);assert.equal(returned.status,'REJECTED');assert.equal(returned.created_by,f.actors.ENTRY.id);assert.equal((await f.s.rows('u_o_reassignments')).length,1);});
test('task completed, locked period, stale version and self-review blocked',async()=>{const f=fixture(),t=await setupTask(f),b={version:1,assigneeId:f.actors.OTHER_ENTRY.id,reviewerId:f.actors.REVIEWER.id,reason:why};await denied(()=>reassignTask(f.s,t.id,{...b,version:0}),'STALE_VERSION');await denied(()=>reassignTask(f.s,t.id,{...b,assigneeId:f.actors.ADMIN.id,reviewerId:f.actors.ADMIN.id}),'SEPARATE_REVIEWER');await f.s.update('u_tasks',t.id,{status:'COMPLETE'});await denied(()=>reassignTask(f.s,t.id,{...b,version:2}),'TASK_NOT_OPEN');f.state.tables.periods[0].status='LOCKED';await denied(()=>reassignTask(f.s,t.id,b),'PERIOD_LOCKED');});
test('failed reassignment rolls back every pending mutation in transaction fixture',async()=>{const f=fixture(),t=await setupTask(f),d=await f.s.insert('u_submissions',{task_id:t.id,status:'DRAFT',created_by:f.actors.ENTRY.id});const orig=f.s.audit.bind(f.s);f.s.audit=async()=>{throw Error('Audit failed');};await assert.rejects(()=>f.s.transaction(s=>reassignTask(s,t.id,{version:1,assigneeId:f.actors.OTHER_ENTRY.id,reviewerId:f.actors.REVIEWER.id,returnPending:true,reason:why})));f.s.audit=orig;assert.equal((await f.s.get('u_submissions',d.id)).status,'DRAFT');assert.equal((await f.s.get('u_tasks',t.id)).assignee_id,f.actors.ENTRY.id);});
test('source transfer changes only ownership and version; old calculation source snapshot unchanged',async()=>{const f=fixture(),src=await source(f),snap={source:structuredClone(src)};const r=await reassignSource(f.s,src.id,{ownershipVersion:1,ownerId:f.actors.OTHER_ENTRY.id,reason:why});assert.equal(r.owner_id,f.actors.OTHER_ENTRY.id);assert.equal(r.ownership_version,2);assert.equal(r.code,src.code);assert.equal(r.unit,src.unit);assert.equal(snap.source.owner_id,f.actors.ENTRY.id);assert.equal(f.state.locks[0],'scope12-governance');await denied(()=>reassignSource(f.s,src.id,{ownershipVersion:1,ownerId:f.actors.ENTRY.id,reason:why}),'STALE_VERSION');});
test('source transfer requires explicit pending return; records retain creator',async()=>{const f=fixture(),src=await source(f),r=await f.s.insert('u_c_records',{source_id:src.id,period_id:f.period,status:'DRAFT',created_by:f.actors.ENTRY.id});const b={ownershipVersion:1,ownerId:f.actors.OTHER_ENTRY.id,reason:why};await denied(()=>reassignSource(f.s,src.id,b),'PENDING_RECORDS');await reassignSource(f.s,src.id,{...b,returnPending:true});assert.equal((await f.s.get('u_c_records',r.id)).status,'REJECTED');assert.equal((await f.s.get('u_c_records',r.id)).created_by,f.actors.ENTRY.id);});
test('resolved/closed corrective action cannot be silently reassigned',async()=>{const f=fixture(),r=await f.s.insert('u_c_actions',{period_id:f.period,owner_id:f.actors.ENTRY.id,status:'CLOSED'});await denied(()=>reassignAction(f.s,r.id,{version:1,ownerId:f.actors.OTHER_ENTRY.id,reason:why}),'INVALID_STATE');});
test('open corrective action reassignment creates immutable history',async()=>{const f=fixture(),r=await f.s.insert('u_c_actions',{period_id:f.period,owner_id:f.actors.ENTRY.id,status:'OPEN'});const next=await reassignAction(f.s,r.id,{version:1,ownerId:f.actors.REVIEWER.id,reason:why});assert.equal(next.owner_id,f.actors.REVIEWER.id);assert.equal((await f.s.rows('u_o_reassignments'))[0].kind,'ACTION');});
test('own notification read is idempotent; someone else cannot read-mark it',async()=>{const f=fixture(),n=await f.s.insert('u_o_notifications',{user_id:f.actors.ENTRY.id,title:'Task assigned',read_at:null});await denied(()=>markRead(f.s,n.id,{}),'NOT_FOUND');const s=f.s.for(f.actors.ENTRY),a=await markRead(s,n.id,{}),b=await markRead(s,n.id,{});assert.equal(a.read_at,b.read_at);});
test('preferences default to explicit booleans and compare current version',async()=>{const f=fixture(),b={version:0,emailEnabled:true,remindersEnabled:false};await denied(()=>preferences(f.s,{...b,emailEnabled:'true'}),'INVALID_PREFERENCE');const p=await preferences(f.s,b);assert.equal(p.user_id,f.s.user.id);assert.equal(p.email_enabled,true);await denied(()=>preferences(f.s,b),'STALE_VERSION');});
test('due reminders exclude complete tasks and future/today due dates',()=>{assert.equal(dueReminder({status:'OPEN',due_date:'2026-10-01'},'2026-10-02'),true);assert.equal(dueReminder({status:'OPEN',due_date:'2026-10-02'},'2026-10-02'),false);assert.equal(dueReminder({status:'COMPLETE',due_date:'2026-10-01'},'2026-10-02'),false);});
test('OCR request snapshots previous extraction and queues once without editing original',async()=>{const f=fixture();Object.assign(f.state.tables.documents[0],{mime_type:'application/pdf'});const before=structuredClone(f.state.tables.documents[0]);const r=await requestOcr(f.s,before.id,{version:1},f.cfg);assert.equal(r.status,'QUEUED');assert.deepEqual(r.previous_extraction,before.extraction);assert.equal(f.state.jobs[0].kind,'OCR_DOCUMENT');assert.deepEqual(f.state.tables.documents[0],before);await denied(()=>requestOcr(f.s,before.id,{version:1},f.cfg),'OCR_PENDING');});
for(const scenario of ['disabled','infected','linked','wrong owner','stale','imported'])test('OCR request rejects '+scenario,async()=>{const f=fixture();Object.assign(f.state.tables.documents[0],{mime_type:'application/pdf'});let cfg=f.cfg,s=f.s,b={version:1},code;if(scenario==='disabled'){cfg={...cfg,ocrEnabled:false};code='OCR_DISABLED';}if(scenario==='infected'){f.state.tables.documents[0].scan_result='INFECTED';code='EVIDENCE_NOT_READY';}if(scenario==='linked'){f.state.tables.documents[0].status='LINKED';code='EVIDENCE_NOT_READY';}if(scenario==='wrong owner'){s=f.s.for(f.actors.OTHER_ENTRY);code='NOT_FOUND';}if(scenario==='stale'){b.version=0;code='STALE_VERSION';}if(scenario==='imported'){const file=await f.s.insert('u_i_files',{document_id:f.document.id});await f.s.insert('u_i_rows',{file_id:file.id,status:'IMPORTED'});code='ALREADY_IMPORTED';}await denied(()=>requestOcr(s,f.document.id,b,cfg),code);assert.equal(f.state.jobs.length,0);});
test('inventory export requires a locked period and never creates an automatic approval',async()=>{const f=fixture();await denied(()=>requestExport(f.s,{periodId:f.period,title:'Inventory',format:'csv'}),'PERIOD_MUST_BE_LOCKED');f.state.tables.periods[0].status='LOCKED';const r=await requestExport(f.s,{periodId:f.period,title:'Inventory',format:'csv'});assert.equal(r.status,'QUEUED');assert.equal(r.period_version,1);assert.equal(f.state.jobs[0].kind,'BUILD_EXPORT');});
test('export queue bounds prevent unrestricted artifact creation',async()=>{const f=fixture();f.state.tables.periods[0].status='LOCKED';for(let i=0;i<3;i++)await requestExport(f.s,{periodId:f.period,title:'Inventory '+i,format:'csv'});await denied(()=>requestExport(f.s,{periodId:f.period,title:'Too many',format:'csv'}),'EXPORT_QUEUE_LIMIT');});
test('export independent approval, expected version and period version all enforced',async()=>{const f=fixture();f.state.tables.periods[0].status='LOCKED';let r=await requestExport(f.s,{periodId:f.period,title:'Inventory',format:'csv'});r=await f.s.update('u_o_exports',r.id,{status:'READY',object_key:'private/key',object_version:'version',sha256:'a'.repeat(64)});const b={version:r.version,decision:'APPROVE',reason:'Reconciled exported rows against locked inventory.'};await denied(()=>reviewExport(f.s,r.id,b),'SELF_APPROVAL');const s=f.s.for(f.actors.REVIEWER);await denied(()=>reviewExport(s,r.id,{...b,version:0}),'STALE_VERSION');f.state.tables.periods[0].version=2;await denied(()=>reviewExport(s,r.id,b),'STALE_REPORT');f.state.tables.periods[0].version=1;const approved=await reviewExport(s,r.id,b);assert.equal(approved.status,'APPROVED');assert.equal(approved.object_key,undefined);});
async function* pages(rows,size=500){for(let i=0;i<rows.length;i+=size)yield rows.slice(i,i+size);}
function inventory(scope='SCOPE_1',extra={}){return {id:id(),ledger:'CORE',record_id:id(),activity_date:'2026-09-01',scope,category:'DIESEL',quantity:'1.000000',unit:'litre',kg_co2e:'0.100000',evidence_count:1,provenance:{method:'SYNTHETIC_TEST'},...extra};}
test('6,001 rows export in pages with exact decimal sum beyond old 5,000 bound',async()=>{const rows=Array.from({length:6001},()=>inventory()),r=await encodeInventory(pages(rows),'csv');assert.equal(r.rowCount,6001);assert.equal(r.totals.primaryKgCo2e,'600.100000');assert.equal(r.sha256,hash(r.bytes));assert.equal(r.bytes.toString().split('\r\n').length,6003);});
test('Scope 2 alternatives, supplemental travel and biogenic disclosure never double count',async()=>{const r=await encodeInventory(pages([inventory('SCOPE_1',{kg_co2e:'10.000000',biogenic_kg:'2.000000'}),inventory('SCOPE_2',{ledger:'CARBON_SCOPE12',kg_co2e:'20.000000',location_kg:'20.000000',market_kg:'5.000000'}),inventory('SCOPE_3',{kg_co2e:'3.000000'}),inventory('SUPPLEMENTAL',{kg_co2e:'7.000000'})]),'jsonl');assert.equal(r.totals.primaryKgCo2e,'33.000000');assert.equal(r.totals.scope2MarketKgCo2e,'5.000000');assert.equal(r.totals.biogenicCo2Kg,'2.000000');assert.equal(r.totals.scopes.SUPPLEMENTAL,'7.000000');});
test('missing market result is unknown, not a fabricated zero',async()=>{const r=await encodeInventory(pages([inventory('SCOPE_2')]),'jsonl');assert.equal(r.totals.scope2MarketKgCo2e,null);assert.equal(r.totals.scope2RowsWithoutMarketResult,1);});
test('CSV escapes formula-leading cells and JSONL keeps source provenance',async()=>{const row=inventory('SCOPE_1',{category:'=2+2'});const csv=await encodeInventory(pages([row]),'csv');assert.match(csv.bytes.toString(),/'=2\+2/);const json=await encodeInventory(pages([row]),'jsonl');assert.deepEqual(JSON.parse(json.bytes).provenance,row.provenance);});
test('export enforces byte/row limits with no partial public artifact',async()=>{await denied(()=>encodeInventory(pages([inventory(),inventory()]),'csv',{maxRows:1}),'EXPORT_ROW_LIMIT');await denied(()=>encodeInventory(pages([inventory()]),'csv',{maxBytes:20}),'EXPORT_BYTE_LIMIT');await denied(()=>encodeInventory(pages([inventory('WRONG')]),'jsonl'),'UNKNOWN_SCOPE');});
test('preview and publication require roles, status, exact size and matching SHA-256',async()=>{const f=fixture(),bytes=Buffer.from('synthetic bytes'),r=await f.s.insert('u_o_exports',{period_id:f.period,created_by:f.actors.ADMIN.id,status:'READY',format:'csv',byte_count:bytes.length,object_key:'test',object_version:'v',sha256:hash(bytes)}),storage={get:async()=>bytes};await denied(()=>downloadExport(f.s,storage,r.id),'APPROVAL_REQUIRED');await denied(()=>downloadExport(f.s.for(f.actors.LEADERSHIP),storage,r.id,{preview:true}),'FORBIDDEN');assert.equal((await downloadExport(f.s,storage,r.id,{preview:true})).bytes.toString(),bytes.toString());await denied(()=>downloadExport(f.s,{get:async()=>Buffer.from('tampered')},r.id,{preview:true}),'EXPORT_INTEGRITY');assert.equal(publicExport(r).object_key,undefined);});
