/** LOOPBACK-ONLY SYNTHETIC UI FIXTURE. Not a production mode or real infrastructure. */
import {writeFile} from 'node:fs/promises';import {once} from 'node:events';
import {createApp} from '../../src/http.mjs';import {id,fail,role,hash,passwordVerify} from '../../src/core.mjs';import {fields} from '../../src/university/core.mjs';import {matchOperation} from '../../src/operations/routes.mjs';import {requestReset,consumeLink,preparePassword} from '../../src/operations/accounts.mjs';import {canReadEvidence} from '../../src/operations/access.mjs';import {fixture,TEST_PASSWORD} from './memory.mjs';
const f=fixture(),cache=new Map(),bytes=Buffer.from('Synthetic invoice evidence; test metadata only.');
Object.assign(f.state.tables.documents[0],{original_name:'SYNTHETIC-scanned-invoice.pdf',mime_type:'application/pdf',file_size:bytes.length,sha256:hash(bytes),created_at:new Date().toISOString()});
await f.s.insert('u_departments',{campus_id:f.campus,name:'Synthetic Estates & Hostels',code:'HOSTELS',owner_id:f.actors.ENTRY.id});
await f.s.insert('u_tasks',{period_id:f.period,campus_id:f.campus,kpi_id:id(),bucket:'2026-09 water meter',assignee_id:f.actors.ENTRY.id,reviewer_id:f.actors.REVIEWER.id,status:'OPEN',version:1});
await f.s.insert('u_c_sources',{code:'DG-TEST',name:'Synthetic backup generator',kind:'STATIONARY_DIESEL',unit:'litre',campus_id:f.campus,owner_id:f.actors.ENTRY.id,ownership_version:1});
await f.s.insert('u_c_actions',{title:'Synthetic invoice evidence review',owner_id:f.actors.ENTRY.id,period_id:f.period,status:'OPEN',version:1});
await f.s.insert('periods',{name:'Synthetic locked export period',start_date:'2025-04-01',end_date:'2026-03-31',status:'LOCKED',version:1});
for(const [i,title]of ['Review September data ownership','Confirm evidence-sharing policy','Prepare the independent report review'].entries())await f.s.notify(f.actors.ADMIN.id,'SYNTHETIC_TEST',id(),title,'Synthetic fixture for native-browser UI validation. Not live university data.','ui-test:'+i);
const cfg={production:false,origins:[],maxInflight:50,maxUploads:2,maxUploadBytes:10485760,metricsToken:'fixture',trustProxy:false};
function store(user){const s=f.s.for(user);s.client={query:async(sql,args)=>{if(sql.includes('FROM cs.u_o_credentials'))return {rows:(f.state.tables.u_o_credentials||[]).map(({id,email,name,role,expires_at,consumed_at,revoked_at,created_at})=>({id,email,name,role,expires_at,consumed_at,revoked_at,created_at}))};if(sql.includes('FROM cs.u_o_mail'))return {rows:(f.state.tables.u_o_mail||[]).map(({id,kind,status,created_at})=>({id,kind,status,created_at:created_at||new Date().toISOString()}))};if(sql.startsWith('SELECT count'))return {rows:[{n:0}]};throw Error('Unsupported fixture SQL');}};return s;}
const services={authenticate:async h=>{const a=f.actors[String(h).replace('Bearer ','')];if(!a)fail(401,'UNAUTHENTICATED','Fixture login needed');return {...a};},limit:async()=>{},login:async b=>{const found=Object.entries(f.actors).find(([,u])=>u.email===b.email&&u.tenant_id===b.tenantId);if(!found||!await passwordVerify(b.password,found[1].password_hash))fail(401,'UNAUTHENTICATED','Fixture login failed');return {token:found[0],user:{id:found[1].id,tenantId:f.tenant,name:'Synthetic QA / '+found[1].name,role:found[1].role}};},logout:async()=>({loggedOut:true}),
 operations:async r=>{const {route,params}=matchOperation(r.method,r.path);role(r.user,route.roles);fields(r.query,route.query);const run=()=>store(r.user).transaction(s=>route.fn(s,r.body,params,r.query,{cfg:f.cfg,storage:{get:async()=>bytes}}));let result;if(r.method!=='GET'&&!route.secret){const key=r.user.id+':'+r.path+':'+r.key,input=JSON.stringify(r.body),old=cache.get(key);if(!r.key)fail(422,'KEY_REQUIRED','Idempotency required');if(old&&old.input!==input)fail(409,'IDEMPOTENCY_CONFLICT','Different input');result=old?structuredClone(old.result):await run();cache.set(key,{input,result:structuredClone(result)});}else result=await run();return route.file?{file:result}:{data:result};},
 account:async r=>{if(r.path.endsWith('/recover'))return requestReset(f.s,r.body,f.cfg);const encoded=await preparePassword(r.body);return f.s.transaction(s=>consumeLink(s,r.body,encoded));},
 listResource:async(user,table,q)=>{if(table==='users')role(user,['ADMIN']);let rows=await store(user).rows(table,{},2000);if(table==='documents')rows=rows.filter(d=>canReadEvidence(user,d,{scope:(f.state.tables.u_o_document_scopes||[]).find(s=>s.document_id===d.id),memberships:f.state.tables.u_o_memberships||[],grants:f.state.tables.u_o_document_grants||[]}));if(table==='users')rows=rows.map(({password_hash,...r})=>r);return {items:rows,nextCursor:null};},
 university:async r=>{const map={'/api/v2/university/departments':'u_departments','/api/v2/university/tasks':'u_tasks','/api/v2/university/carbon/sources':'u_c_sources','/api/v2/university/carbon/actions':'u_c_actions'};if(r.method!=='GET'||!map[r.path])fail(404,'NOT_FOUND','Fixture only');return {data:await store(r.user).listPage(map[r.path],{},r.query)};},
 download:async(user,rid)=>{const d=await store(user).get('documents',rid);return {name:d.original_name,mime:d.mime_type,bytes};}
};
const app=createApp(cfg,services,{log:()=>{}});app.server.listen(0,'127.0.0.1');await once(app.server,'listening');const base='http://127.0.0.1:'+app.server.address().port;cfg.origins.push(base);const info={base,tenantId:f.tenant,email:f.actors.ADMIN.email,password:TEST_PASSWORD,actors:Object.fromEntries(Object.entries(f.actors).map(([k,u])=>[k,{id:u.id,email:u.email}]))};if(process.env.UI_FIXTURE_INFO)await writeFile(process.env.UI_FIXTURE_INFO,JSON.stringify(info),{mode:0o600});console.log(JSON.stringify({base,synthetic:true,note:'Test fixture auth, DB, scanner, storage. Do not deploy.'}));
