/** Worker control-flow with explicit SQL adapter doubles. No real PostgreSQL/RLS or S3. */
import test from 'node:test';import assert from 'node:assert/strict';import {id,hash} from '../../src/core.mjs';import {processOcr,runOcr} from '../../src/operations/ocr.mjs';import {processExport} from '../../src/operations/exports.mjs';import {processMail} from '../../src/operations/mail.mjs';import {processSweep} from '../../src/operations/reminders.mjs';import {seal} from '../../src/operations/crypto.mjs';
function fixture(){const tenant=id(),job={id:id(),tenant_id:tenant,entity_id:id(),lease_token:id()},bytes=Buffer.from('synthetic original'),doc={id:id(),tenant_id:tenant,status:'REVIEW_REQUIRED',scan_result:'CLEAN',sha256:hash(bytes),file_size:bytes.length,mime_type:'application/pdf',version:1,object_key:'original',object_version:'v1'},run={id:job.entity_id,document_id:doc.id,document_version:1,input_sha256:doc.sha256,status:'QUEUED'},report={id:job.entity_id,period_id:id(),period_version:1,format:'csv',status:'QUEUED'},cfg={ocrEnabled:true,encryptionKey:'b'.repeat(64),mailMode:'capture',exportMaxRows:100000,exportMaxBytes:33554432};const state={tenantStatus:'ACTIVE',lease:true,doc,run,report,period:{status:'LOCKED',version:1},imported:false,queries:[],pages:[],writes:[],mail:null,credential:null,user:{active:true,role:'ADMIN'},put:[],engine:0,delivered:0};const client={release(){},async query(sql,args=[]){state.queries.push([sql,args]);if(sql.startsWith('SELECT * FROM cs.jobs'))return {rows:state.lease?[job]:[]};if(sql.includes('SELECT status FROM cs.tenants'))return {rows:[{status:state.tenantStatus}]};if(sql.startsWith('SELECT * FROM cs.u_o_ocr_runs'))return {rows:[state.run]};if(sql.startsWith('SELECT * FROM cs.documents'))return {rows:state.doc?[structuredClone(state.doc)]:[]};if(sql.startsWith('SELECT 1 FROM cs.u_i_rows'))return {rows:state.imported?[{present:1}]:[]};if(sql.startsWith('SELECT * FROM cs.u_o_exports'))return {rows:[state.report]};if(sql.startsWith('SELECT status,version FROM cs.periods'))return {rows:[state.period]};if(sql.startsWith('SELECT i.*'))return {rows:state.pages.shift()||[]};if(sql.startsWith('SELECT * FROM cs.u_o_mail'))return {rows:state.mail?[state.mail]:[]};if(sql.startsWith('SELECT * FROM cs.u_o_credentials'))return {rows:state.credential?[state.credential]:[]};if(sql.includes(' FROM cs.users'))return {rows:[state.user]};if(sql.startsWith('UPDATE')||sql.startsWith('INSERT'))state.writes.push([sql,args]);return {rows:[],rowCount:1};}};const pool={connect:async()=>client},storage={get:async()=>bytes,put:async(...args)=>{state.put.push(args);return {versionId:'export-v1'};}},engine=async()=>{state.engine++;return {engine:'SYNTHETIC_OCR_DOUBLE',pageCount:1,ocrPages:1,pages:[{page:1,text:'test'}],needsHumanReview:true};};return {tenant,job,bytes,cfg,state,pool,storage,engine};}
const rejects=(fn,code)=>assert.rejects(fn,e=>e.code===code);
for(const kind of ['lease','suspended','stale','infected','disabled'])test('OCR worker rejects '+kind+' before invoking an engine',async()=>{const f=fixture();let code;if(kind==='lease'){f.state.lease=false;code='LEASE_LOST';}if(kind==='suspended'){f.state.tenantStatus='SUSPENDED';code='TENANT_SUSPENDED';}if(kind==='stale'){f.state.doc.version++;code='OCR_STALE_DOCUMENT';}if(kind==='infected'){f.state.doc.scan_result='INFECTED';code='OCR_STALE_DOCUMENT';}if(kind==='disabled'){f.cfg.ocrEnabled=false;code='OCR_DISABLED';}await rejects(()=>processOcr(f.pool,f.storage,f.job,f.cfg,f.engine),code);assert.equal(f.state.engine,0);});
test('OCR worker checks original hash before invoking an engine',async()=>{const f=fixture();f.storage.get=async()=>Buffer.from('tampered');await rejects(()=>processOcr(f.pool,f.storage,f.job,f.cfg,f.engine),'EVIDENCE_INTEGRITY');assert.equal(f.state.engine,0);});
for(const kind of ['lease','version','import'])test('OCR rechecks '+kind+' before replacing suggestions',async()=>{const f=fixture(),engine=async()=>{if(kind==='lease')f.state.lease=false;if(kind==='version')f.state.doc.version++;if(kind==='import')f.state.imported=true;return f.engine();};await rejects(()=>processOcr(f.pool,f.storage,f.job,f.cfg,engine),{lease:'LEASE_LOST',version:'OCR_STALE_DOCUMENT',import:'ALREADY_IMPORTED'}[kind]);assert.ok(!f.state.writes.some(([sql])=>sql.startsWith('UPDATE cs.documents')));});
test('completed OCR updates suggestions and audit but never originals or approved inventory',async()=>{const f=fixture();await processOcr(f.pool,f.storage,f.job,f.cfg,f.engine);assert.equal(f.state.engine,1);assert.equal(f.state.put.length,0);assert.ok(f.state.writes.some(([sql])=>sql.startsWith('UPDATE cs.documents SET extraction=')));assert.ok(f.state.writes.some(([sql,args])=>sql.startsWith('INSERT INTO cs.audit_events')&&args[2]==='O_OCR_COMPLETED'));assert.ok(!f.state.writes.some(([sql])=>/calculations|u_inventory/.test(sql)));});
test('OCR adapter rejects unsupported MIME and unavailable executable without running OCR',async()=>{assert.throws(()=>runOcr(Buffer.from('x'),'application/zip'),/Unsupported/);await rejects(()=>runOcr(Buffer.from('x'),'application/pdf',{python:'/definitely/not/an/interpreter',timeoutMs:3000}),'OCR_UNAVAILABLE');});
test('export processor uses locked snapshot, exact versioned bytes and lease-specific object key',async()=>{const f=fixture();f.state.pages=[[{id:id(),ledger:'CORE',record_id:id(),scope:'SCOPE_1',kg_co2e:'1.250000',quantity:'1.000000',unit:'litre'}]];await processExport(f.pool,f.storage,f.job,f.cfg);assert.equal(f.state.put.length,1);assert.match(f.state.put[0][0],new RegExp(f.job.lease_token));assert.ok(f.state.queries.some(([sql])=>sql==='BEGIN ISOLATION LEVEL REPEATABLE READ'));const write=f.state.writes.find(([sql])=>sql.includes("SET status='READY'"));assert.equal(write[1][2],1);assert.equal(write[1][6],'export-v1');assert.equal(JSON.parse(write[1][7]).primaryKgCo2e,'1.250000');});
test('export rejects a reopened/version-changed period before storage',async()=>{const f=fixture();f.state.period.version=2;await rejects(()=>processExport(f.pool,f.storage,f.job,f.cfg),'STALE_REPORT');assert.equal(f.state.put.length,0);});
test('stale export worker cannot publish even when an orphan attempt object was written',async()=>{const f=fixture();f.storage.put=async(...args)=>{f.state.put.push(args);f.state.lease=false;return {versionId:'orphan-attempt'};};await rejects(()=>processExport(f.pool,f.storage,f.job,f.cfg),'LEASE_LOST');assert.equal(f.state.put.length,1);assert.ok(!f.state.writes.some(([sql])=>sql.includes("SET status='READY'")));});
function mail(f){const m={id:f.job.entity_id,tenant_id:f.tenant,status:'PENDING',user_id:id(),kind:'NOTIFICATION',envelope:seal({to:'synthetic@test.invalid',subject:'Test',text:'Fixture message'},f.cfg.encryptionKey,`${f.tenant}:${f.job.entity_id}`)};f.state.mail=m;return m;}
test('mail processor cancels inactive recipients without external delivery',async()=>{const f=fixture();mail(f);f.state.user.active=false;await processMail(f.pool,f.job,f.cfg,async()=>{f.state.delivered++;});assert.equal(f.state.delivered,0);assert.ok(f.state.writes.some(([sql])=>sql.includes("status='CANCELLED'")));});
test('mail processor removes encrypted payload after acknowledged capture',async()=>{const f=fixture();mail(f);await processMail(f.pool,f.job,f.cfg,async()=>{f.state.delivered++;return {status:'CAPTURED',deliveryId:f.job.entity_id};});assert.equal(f.state.delivered,1);assert.ok(f.state.writes.some(([sql])=>sql.includes('envelope=NULL')&&sql.includes('delivery_id')));});
test('revoked credential mail is cancelled without decrypting or delivering',async()=>{const f=fixture(),m=mail(f);m.credential_id=id();m.envelope='not-an-envelope';f.state.credential={id:m.credential_id,purpose:'INVITE',revoked_at:new Date().toISOString(),expires_at:new Date(Date.now()+100000).toISOString()};await processMail(f.pool,f.job,f.cfg,async()=>{f.state.delivered++;});assert.equal(f.state.delivered,0);});
test('suspended universities defer recurring reminder sweep without reading tasks',async()=>{const f=fixture();f.state.tenantStatus='SUSPENDED';assert.deepEqual(await processSweep(f.pool,f.job,f.cfg),{suspended:true});assert.ok(!f.state.queries.some(([sql])=>sql.includes('FROM cs.u_tasks')));assert.ok(f.state.writes.some(([sql])=>sql.includes("interval '1 hour'")));});
