import { uuid,scaled,format,sum,ratio,percentOf,csvWrite,fail } from '../core.mjs';
import { activeBoundary,liveRecords } from './service.mjs';
import { gaps,intervalDays,ZERO } from './core.mjs';
export function summarize(rows,boundary){const direct=rows.filter(r=>r.scope==='SCOPE_1'),energy=rows.filter(r=>r.scope==='SCOPE_2'),scope1=sum(direct.map(r=>r.scope1_kg)),location=sum(energy.map(r=>r.location_kg)),biogenic=sum(rows.map(r=>r.biogenic_kg));
 const marketComplete=boundary?.scope2_mode==='DUAL'&&energy.every(r=>r.market_kg!==null&&r.market_kg!==undefined),market=marketComplete?sum(energy.map(r=>r.market_kg)):null;
 const gases=new Map();for(const r of direct)for(const g of r.provenance.primary.gases){const old=gases.get(g.gas)||{gas:g.gas,massKg:ZERO,kgCo2e:g.gas==='CO2_BIOGENIC'?null:ZERO};old.massKg=sum([old.massKg,g.massKg]);if(g.kgCo2e!==null)old.kgCo2e=sum([old.kgCo2e,g.kgCo2e]);gases.set(g.gas,old);}
 const campuses=new Map();for(const r of rows){const c=campuses.get(r.campus_id)||{campusId:r.campus_id,scope1Kg:ZERO,scope2LocationKg:ZERO,scope2MarketKg:boundary?.scope2_mode==='DUAL'?ZERO:null};if(r.scope==='SCOPE_1')c.scope1Kg=sum([c.scope1Kg,r.scope1_kg]);else{c.scope2LocationKg=sum([c.scope2LocationKg,r.location_kg]);c.scope2MarketKg=c.scope2MarketKg===null||r.market_kg==null?null:sum([c.scope2MarketKg,r.market_kg]);}campuses.set(r.campus_id,c);}
 return {scope1:{kgCo2e:scope1,biogenicCo2Kg:biogenic,byGas:[...gases.values()],aggregatedFactorRecords:direct.filter(r=>!r.provenance.primary.gasBreakdownAvailable).length},scope2:{locationKgCo2e:location,marketKgCo2e:market,marketResultComplete:marketComplete,method:boundary?.scope2_mode||null},scope12LocationKgCo2e:sum([scope1,location]),scope12MarketKgCo2e:market===null?null:sum([scope1,market]),recordCount:rows.length,estimatedRecords:rows.filter(r=>r.data_quality==='ESTIMATED').length,campuses:[...campuses.values()],arithmetic:'Scope 1 + location-based Scope 2 is the primary inventory. Market-based Scope 2 is an alternative, not an extra emission. Biogenic CO2 is separate.',completeInventoryClaim:false};
}
export async function readiness(s,pid){const period=await s.period(uuid(pid),false),boundary=await activeBoundary(s,pid,{required:false}),blockers=[],warnings=[];if(!boundary)return {active:false,ready:false,period,blockers:[{code:'BOUNDARY_REQUIRED',message:'No independently approved Scope 1/2 boundary.'}],warnings,sourceCoverage:[]};
 if(await s.count('u_c_boundaries',{period_id:pid,status:'DRAFT'}))blockers.push({code:'PENDING_BOUNDARY_REVIEW',message:'Review the pending boundary revision before freezing a report.'});
 const rows=await liveRecords(s,pid),all=await s.rows('u_c_records',{period_id:pid},5000),calculated=rows.filter(r=>r.status==='CALCULATED'),sourceCoverage=[];
 for(const item of boundary.sources){const source=item.sourceSnapshot,from=source.active_from>period.start_date?source.active_from:period.start_date,to=source.active_to<period.end_date?source.active_to:period.end_date;const missing=item.decision==='INCLUDED'?gaps(from,to,calculated.filter(r=>r.source_id===source.id)):[];
  const expected=intervalDays(from,to),missingDays=missing.reduce((n,g)=>n+intervalDays(g.from,g.to),0);sourceCoverage.push({sourceId:source.id,code:source.code,name:source.name,campusId:source.campus_id,kind:source.kind,decision:item.decision,rationale:item.rationale,expectedDays:expected,coveredDays:item.decision==='INCLUDED'?expected-missingDays:null,missingIntervals:missing,frequency:item.frequency});if(missing.length)blockers.push({code:'SOURCE_GAPS',sourceId:source.id,message:'Included source has uncovered reporting dates.',missingIntervals:missing});}
 const sources=await s.rows('u_c_sources',{campus_id:boundary.campus_ids},1000);for(const src of sources)if(src.active_from<=period.end_date&&src.active_to>=period.start_date&&!boundary.sources.some(x=>x.sourceId===src.id))blockers.push({code:'UNASSESSED_SOURCE',sourceId:src.id,message:'Source was registered after this boundary snapshot; review a new boundary revision before reporting.'});
 const pending=all.filter(r=>['DRAFT','SUBMITTED','REJECTED'].includes(r.status));if(pending.length)blockers.push({code:'PENDING_RECORDS',count:pending.length,message:'Approve, correct or cancel every pending Scope 1/2 entry.'});
 const pendingVoids=(await s.rows('u_c_voids',{period_id:pid,status:'SUBMITTED'},5000)).filter(v=>all.some(r=>r.id===v.record_id));if(pendingVoids.length)blockers.push({code:'PENDING_VOIDS',count:pendingVoids.length,message:'Review pending correction requests.'});
 const actions=await s.rows('u_c_actions',{period_id:pid},5000),unclosed=actions.filter(a=>a.status!=='CLOSED'),critical=unclosed.filter(a=>['HIGH','CRITICAL'].includes(a.severity));if(critical.length)blockers.push({code:'UNRESOLVED_FINDINGS',count:critical.length,message:'High or critical corrective actions must be independently closed.'});if(unclosed.length>critical.length)warnings.push({code:'LOWER_SEVERITY_FINDINGS',count:unclosed.length-critical.length});
 if(boundary.scope2_mode==='LOCATION_ONLY')warnings.push({code:'LOCATION_ONLY',message:'No market-based total is asserted. Applicability of dual reporting remains a reviewed boundary decision.'});
 if(calculated.some(r=>r.data_quality==='ESTIMATED'))warnings.push({code:'ESTIMATES_INCLUDED',message:'Estimated records are included with their disclosed assumptions.'});
 return {active:true,ready:blockers.length===0,period,boundaryId:boundary.id,boundaryRevision:boundary.revision,blockers,warnings,sourceCoverage,actions:unclosed.map(a=>({id:a.id,title:a.title,severity:a.severity,dueDate:a.due_date,ownerId:a.owner_id,status:a.status,overdue:a.due_date<new Date().toISOString().slice(0,10)})),completeness:'Readiness applies to the declared source register, not an external assurance of all university sources.'};
}
export async function snapshot(s,pid){if(!await s.count('u_c_period_modes',{period_id:uuid(pid)}))return {active:false,note:'Legacy inventory period; enhanced controls are not applied retrospectively.'};const boundary=await activeBoundary(s,pid),rows=await s.carbonActive(pid),ready=await readiness(s,pid),summary=summarize(rows,boundary);return {schemaVersion:'scope12-report-1',active:true,boundary,summary,readiness:ready,calculationRows:rows,standardsBaseline:'GHG Protocol Corporate Standard and Scope 2 Guidance (2015), reviewed configurable factors. No automatic adoption of consultation drafts.',assurance:'INTERNAL_ONLY',limits:['Instrument eligibility, factor completeness and source coverage require competent review.','Certificates are not verified against external registries.','No offsets or projected savings are subtracted.','Owned solar generation/export is not automatically an avoided-emissions or zero-emission claim.']};}
export async function dashboard(s,pid){const data=await snapshot(s,pid);if(!data.active)return {...data,readiness:await readiness(s,pid)};return {active:true,asOf:new Date().toISOString(),period:data.readiness.period,summary:data.summary,readiness:data.readiness,boundary:{id:data.boundary.id,revision:data.boundary.revision,approach:data.boundary.approach,scope2Mode:data.boundary.scope2_mode},engine:'EXACT_DATABASE_VALUES_NO_AI'};}
export async function liveExport(s,pid){const data=await snapshot(s,pid);if(!data.active)fail(409,'BOUNDARY_REQUIRED','Activate enhanced Scope 1/2 for this period first.');const columns=['recordId','sourceId','intervalStart','intervalEnd','scope','kind','quantity','unit','scope1Kg','scope2LocationKg','scope2MarketKg','biogenicCo2Kg','quality'];const rows=data.calculationRows.map(r=>[r.record_id,r.source_id,r.interval_start,r.interval_end,r.scope,r.kind,r.quantity,r.unit,r.scope1_kg,r.location_kg,r.market_kg,r.biogenic_kg,r.data_quality]);return {name:'CarbonSynq-Scope12-live-'+pid+'.csv',mime:'text/csv; charset=utf-8',bytes:csvWrite(columns,rows)};}
export function selectedInventoryTotal(snap,scopes,basis='LOCATION'){let total=sum(snap.inventoryRows.filter(r=>scopes.includes(r.scope)).map(r=>r.kg_co2e));if(basis==='MARKET'&&scopes.includes('SCOPE_2')){const c=snap.scope12;if(!c?.active||!c.summary.scope2.marketResultComplete||c.summary.scope2.marketKgCo2e===null)fail(422,'MARKET_REPORT_REQUIRED','Market-based targets require a complete enhanced dual-reporting snapshot.');total=format(scaled(total)-scaled(snap.inventorySummary.scopes.SCOPE_2)+scaled(c.summary.scope2.marketKgCo2e));}return total;}
