/** Integrated university Scope 1/2 application service.
 * Every exported write is called inside the shared tenant transaction and idempotency wrapper.
 * Period-scoped advisory locks serialize final allocation/overlap decisions across API instances.
 */
import { version,role } from '../../core.mjs';
import { fields,uuid,text,reason,choice,day,decimal,scaled,format,sum,evidenceIds,overlaps,csvParse,fail } from '../core.mjs';
import { authorOnly,independent } from '../collection.mjs';
import { SOURCE_KINDS,CHECKLIST,EXTRA_KPIS } from './catalog.mjs';
import * as rules from './core.mjs';
const WRITE=['ADMIN','ENTRY'],REVIEW=['ADMIN','REVIEWER'];
export async function lockPeriod(s,pid){await s.lockKey('scope12-governance');const p=await s.period(uuid(pid));await s.lockKey('scope12-period:'+p.id);return p;}
export async function activeBoundary(s,pid,{required=true}={}){const rows=await s.rows('u_c_boundaries',{period_id:uuid(pid),status:'APPROVED'},100);const r=rows.sort((a,b)=>b.revision-a.revision)[0];if(!r&&required)fail(409,'BOUNDARY_REQUIRED','Register sources, assess the campus boundary and independently approve the Scope 1/2 plan first.');return r||null;}
export async function liveRecords(s,pid){const records=await s.rows('u_c_records',{period_id:pid},5000),voids=await s.rows('u_c_voids',{period_id:pid,status:'APPROVED'},5000);const omitted=new Set(voids.map(v=>v.record_id));return records.filter(r=>!['CANCELLED','REJECTED'].includes(r.status)&&!omitted.has(r.id));}
export async function sourceAccess(s,source){if(s.user.role==='ENTRY'&&source.owner_id!==s.user.id)fail(404,'NOT_FOUND','Source not found.');}
export function recordAccess(s,r){if(s.user.role==='ENTRY'&&r.created_by!==s.user.id)fail(404,'NOT_FOUND','Record not found.');}
export async function createSource(s,b){role(s.user,['ADMIN']);const a=rules.sourceInput(b);await s.location(a.campus_id,a.department_id);await s.userRef(a.owner_id,['ADMIN','ENTRY']);
 if(a.building_id){const building=await s.get('buildings',a.building_id);if(building.campus_id!==a.campus_id)fail(422,'BUILDING_CAMPUS','Building does not belong to this campus.');}
 const r=await s.insert('u_c_sources',{...a,created_by:s.user.id});await s.audit('C_SOURCE_REGISTERED',r.id,{code:r.code,kind:r.kind,scope:r.scope});return r;}
export async function installExtraKpis(s,b){role(s.user,['ADMIN']);fields(b,[]);await s.lockKey('scope12-kpi-install');let added=0;
 for(const t of EXTRA_KPIS){if(await s.count('u_kpis',{code:t.code}))continue;await s.insert('u_kpis',{code:t.code,name:t.name,domain:t.domain,unit:t.unit,aggregation:t.aggregation,evidence_required:true,max_value:null,guidance:t.guidance,created_by:s.user.id});added++;}
 await s.audit('C_EXTRA_KPIS_INSTALLED',null,{added});return {added,definitions:EXTRA_KPIS.length,measurementsSeeded:false,factorsSeeded:false};}
export async function createFactor(s,b){role(s.user,REVIEW);const r=await s.insert('u_c_factors',{...rules.factorInput(b),status:'DRAFT',approved_by:null,created_by:s.user.id});await s.audit('C_FACTOR_DRAFTED',r.id,{version:r.version_label});return r;}
export async function editFactor(s,rid,b){role(s.user,REVIEW);const {version:expected,...input}=b,values=rules.factorInput(input),old=await s.get('u_c_factors',uuid(rid),{lock:true});version(old,expected);authorOnly(s.user,old);if(!['DRAFT','REJECTED'].includes(old.status))fail(409,'INVALID_STATE','An approved factor cannot change; create a new version.');const r=await s.update('u_c_factors',old.id,{...values,status:'DRAFT',rejection_reason:null});await s.audit('C_FACTOR_EDITED',r.id);return r;}
export async function reviewFactor(s,rid,action,b){role(s.user,REVIEW);fields(b,['version','reason']);const old=await s.get('u_c_factors',uuid(rid),{lock:true});version(old,b.version);independent(s.user,old);if(old.status!=='DRAFT')fail(409,'INVALID_STATE','Only a draft factor can be reviewed.');choice(action,['approve','reject'],'action');
 const r=await s.update('u_c_factors',old.id,{status:action==='approve'?'APPROVED':'REJECTED',approved_by:action==='approve'?s.user.id:null,rejection_reason:action==='reject'?reason(b.reason):null});await s.audit('C_FACTOR_'+r.status,r.id,{source:r.source,version:r.version_label});return r;}
async function validateBoundary(s,a,p){
 const campuses=await s.rows('campuses',{},200),declared=new Set([...a.campus_ids,...a.campus_exclusions.map(c=>c.campusId)]);
 if(campuses.some(c=>!declared.has(c.id))||declared.size!==campuses.length)fail(422,'CAMPUS_COVERAGE','Include or explicitly exclude every registered campus.');
 const src=await s.rows('u_c_sources',{campus_id:a.campus_ids},1000),active=src.filter(x=>x.active_from<=p.end_date&&x.active_to>=p.start_date),ids=new Set(a.sources.map(x=>x.sourceId));
 if(active.some(x=>!ids.has(x.id)))fail(422,'SOURCE_COVERAGE','Assess every active registered source in the included campuses.');
 if(a.base_year>Number(p.end_date.slice(0,4)))fail(422,'BASE_YEAR','The baseline year cannot be after this inventory period.');
 for(const x of a.sources){const source=await s.get('u_c_sources',x.sourceId);if(!a.campus_ids.includes(source.campus_id))fail(422,'SOURCE_BOUNDARY','Every declared source must belong to an included campus.');
  if(source.active_from>p.end_date||source.active_to<p.start_date)fail(422,'SOURCE_DATES','Do not include inactive-period sources in this period plan.');
  await s.evidence(x.evidenceIds,x.decision==='NO_ACTIVITY');x.sourceSnapshot=source;}
 const byCheck=new Map(a.screening.map(x=>[x.campusId+':'+x.code,x]));
 for(const cid of a.campus_ids)for(const c of CHECKLIST){const row=byCheck.get(cid+':'+c.code);if(!row)fail(422,'SCREENING_REQUIRED','Complete the university Scope 1/2 source checklist for every included campus.');
  const matching=a.sources.filter(x=>x.sourceSnapshot.campus_id===cid&&(c.kind==='THERMAL_ENERGY'?['PURCHASED_STEAM','PURCHASED_HEAT','PURCHASED_COOLING'].includes(x.sourceSnapshot.kind):x.sourceSnapshot.kind===c.kind));
  if(c.kind!=='SOLAR_ATTRIBUTES'&&row.decision==='PRESENT'&&!matching.length)fail(422,'UNREGISTERED_SOURCE','A present source category must have at least one registered, assessed source.');
  if(c.kind!=='SOLAR_ATTRIBUTES'&&row.decision==='NOT_APPLICABLE'&&matching.some(x=>x.decision==='INCLUDED'))fail(422,'SCREENING_CONFLICT','An included source contradicts a not-applicable checklist answer.');}
 if(a.screening.some(x=>!a.campus_ids.includes(x.campusId)))fail(422,'SCREENING_CAMPUS','Checklist rows must refer to included campuses only.');await s.evidence(a.evidence_ids,false);return a;
}
export async function createBoundary(s,b){role(s.user,['ADMIN']);let a=rules.boundaryInput(b);const p=await lockPeriod(s,a.period_id);a=await validateBoundary(s,a,p);
 const prior=await s.rows('u_c_boundaries',{period_id:p.id},100);if(prior.some(r=>r.status==='DRAFT'))fail(409,'PENDING_BOUNDARY','Edit or review the existing draft plan before creating another.');
 const revision=prior.reduce((n,r)=>Math.max(n,r.revision),0)+1;const r=await s.insert('u_c_boundaries',{...a,revision,status:'DRAFT',approved_by:null,created_by:s.user.id});await s.audit('C_BOUNDARY_DRAFTED',r.id,{revision,scope2Mode:r.scope2_mode});return r;}
export async function editBoundary(s,rid,b){role(s.user,['ADMIN']);const {version:expected,...input}=b;let a=rules.boundaryInput(input);const seen=await s.get('u_c_boundaries',uuid(rid));if(seen.period_id!==a.period_id)fail(422,'IMMUTABLE_REFERENCE','Boundary reporting period cannot change.');const p=await lockPeriod(s,a.period_id),old=await s.get('u_c_boundaries',seen.id,{lock:true});version(old,expected);authorOnly(s.user,old);if(old.status!=='DRAFT')fail(409,'INVALID_STATE','Create a new boundary revision after review.');a=await validateBoundary(s,a,p);const r=await s.update('u_c_boundaries',old.id,a);await s.audit('C_BOUNDARY_EDITED',r.id);return r;}
export async function reviewBoundary(s,rid,action,b){role(s.user,REVIEW);fields(b,['version','reason']);const seen=await s.get('u_c_boundaries',uuid(rid)),p=await lockPeriod(s,seen.period_id),old=await s.get('u_c_boundaries',seen.id,{lock:true});version(old,b.version);independent(s.user,old);if(old.status!=='DRAFT')fail(409,'INVALID_STATE','Only a draft boundary can be reviewed.');choice(action,['approve','reject'],'action');
 if(action==='reject'){const r=await s.update('u_c_boundaries',old.id,{status:'REJECTED',rejection_reason:reason(b.reason)});await s.audit('C_BOUNDARY_REJECTED',r.id);return r;}
 await validateBoundary(s,structuredClone(old),p);await s.evidence(old.evidence_ids,true);
 if((await liveRecords(s,p.id)).length)fail(409,'ACTIVE_CARBON_RECORDS','Void calculated rows and cancel drafts before replacing their accounting boundary. Existing snapshots are never silently reinterpreted.');
 const legacy=(await s.rows('activities',{period_id:p.id},5000)).filter(r=>r.status!=='REJECTED');const prior=(await s.rows('u_emissions',{period_id:p.id,scope:['SCOPE_1','SCOPE_2']},5000)).filter(r=>r.status!=='REJECTED');
 if(legacy.length||prior.length)fail(409,'LEGACY_SCOPE12_EXISTS','This period contains legacy Scope 1/2 records. Use a clean period or a reviewed migration; do not post the same consumption in two ledgers.');
 const r=await s.update('u_c_boundaries',old.id,{status:'APPROVED',approved_by:s.user.id});if(!await s.count('u_c_period_modes',{period_id:p.id}))await s.insert('u_c_period_modes',{period_id:p.id,boundary_id:r.id,activated_by:s.user.id});
 await s.audit('C_BOUNDARY_APPROVED',r.id,{revision:r.revision,mode:'EXCLUSIVE_SCOPE12',scope2Mode:r.scope2_mode});return r;}
async function validateInstrument(s,a){const p=await s.period(a.period_id),tenant=await s.get('tenants',s.tenant),factor=await s.get('u_c_factors',a.factor_id);
 if(a.valid_from<p.start_date||a.valid_to>p.end_date)fail(422,'INSTRUMENT_PERIOD','Consumption eligibility dates must be inside the selected reporting period.');
 if(factor.status!=='APPROVED'||factor.use!=='MARKET_CONTRACT'||factor.unit!=='kWh'||factor.region!==a.region||factor.valid_from>a.valid_from||factor.valid_to<a.valid_to)fail(422,'INSTRUMENT_FACTOR','Use an approved contractual energy factor with matching region and complete eligibility dates.');
 if(a.kind==='EAC'&&factor.substance!=='ELECTRICITY')fail(422,'EAC_COMMODITY','EAC instruments here are electricity only; thermal supplier factors need their own reviewed product allocation.');
 const normalize=v=>v.trim().replace(/\s+/g,' ').toLowerCase();if(normalize(a.beneficiary)!==normalize(tenant.name))fail(422,'INSTRUMENT_BENEFICIARY','Retirement/allocation beneficiary must match this university name.');await s.evidence(a.evidence_ids,true);return factor;}
export async function createInstrument(s,b){role(s.user,REVIEW);const a=rules.instrumentInput(b);await lockPeriod(s,a.period_id);await validateInstrument(s,a);
 if(await s.count('u_c_instruments',{serial_key:a.serial_key}))fail(409,'DUPLICATE_INSTRUMENT','This registry and serial are already registered for the tenant.');
 const r=await s.insert('u_c_instruments',{...a,status:'DRAFT',approved_by:null,created_by:s.user.id});await s.audit('C_INSTRUMENT_DRAFTED',r.id,{serialKey:r.serial_key,quantityKwh:r.quantity_kwh});return r;}
export async function editInstrument(s,rid,b){role(s.user,REVIEW);const {version:expected,...input}=b,a=rules.instrumentInput(input),seen=await s.get('u_c_instruments',uuid(rid));if(a.period_id!==seen.period_id||a.serial_key!==seen.serial_key)fail(422,'IMMUTABLE_REFERENCE','Keep the registered period, registry and serial.');await lockPeriod(s,seen.period_id);const old=await s.get('u_c_instruments',seen.id,{lock:true});version(old,expected);authorOnly(s.user,old);if(!['DRAFT','REJECTED'].includes(old.status))fail(409,'INVALID_STATE','Approved instruments are immutable.');await validateInstrument(s,a);const r=await s.update('u_c_instruments',old.id,{...a,status:'DRAFT',rejection_reason:null});await s.audit('C_INSTRUMENT_EDITED',r.id);return r;}
export async function reviewInstrument(s,rid,action,b){role(s.user,REVIEW);fields(b,['version','reason']);const seen=await s.get('u_c_instruments',uuid(rid));await lockPeriod(s,seen.period_id);const old=await s.get('u_c_instruments',seen.id,{lock:true});version(old,b.version);independent(s.user,old);if(old.status!=='DRAFT')fail(409,'INVALID_STATE','Instrument is not awaiting review.');choice(action,['approve','reject'],'action');if(action==='approve')await validateInstrument(s,old);
 const r=await s.update('u_c_instruments',old.id,{status:action==='approve'?'APPROVED':'REJECTED',approved_by:action==='approve'?s.user.id:null,rejection_reason:action==='reject'?reason(b.reason):null});await s.audit('C_INSTRUMENT_'+r.status,r.id,{review:'INTERNAL_ONLY_NOT_REGISTRY_VALIDATED'});return r;}
export async function preflight(s,a,{excludeId=null,forApproval=false}={}){
 const period=await s.period(a.period_id),boundary=await activeBoundary(s,a.period_id),source=await s.get('u_c_sources',a.source_id);if(!forApproval)await sourceAccess(s,source);
 const decision=boundary.sources.find(x=>x.sourceId===source.id);if(decision?.decision!=='INCLUDED')fail(422,'SOURCE_NOT_INCLUDED','Only included sources from the approved boundary can produce inventory records.');
 if(a.interval_start<period.start_date||a.interval_end>period.end_date||a.interval_start<source.active_from||a.interval_end>source.active_to)fail(422,'DATE_OUTSIDE_PERIOD','The entire interval must be inside the source active dates and reporting period.');
 const q=rules.normalizedQuantity(a.quantity_input,source);decimal(q.quantity,'derived quantity',6,true);if(scaled(q.quantity)===0n)reason(a.zero_reason);
 const factor=await s.get('u_c_factors',a.factor_id);rules.checkFactor(a,source,factor,[source.scope==='SCOPE_1'?'DIRECT':'LOCATION']);const evidence=await s.evidence(a.evidence_ids,forApproval);
 const live=await liveRecords(s,period.id);for(const old of live){if(old.id===excludeId)continue;if(old.source_id===source.id&&overlaps(old,a))fail(409,'OVERLAPPING_SOURCE_INTERVAL','This source already has an overlapping active interval. Split independent meters/fuels into distinct registered sources or use an approved correction.');}
 const duplicate=await s.rows('u_c_records',{external_key:a.external_key},1);if(duplicate.some(r=>r.id!==excludeId))fail(409,'DUPLICATE_SOURCE_KEY','This source/document key is already registered.');
 if(a.replaces_id){const replaced=await s.get('u_c_records',a.replaces_id);if(replaced.source_id!==a.source_id||replaced.period_id!==a.period_id)fail(422,'CORRECTION_REFERENCE','A replacement must use the same source and period.');if(!await s.count('u_c_voids',{record_id:replaced.id,status:'APPROVED'}))fail(409,'VOID_REQUIRED','An independently approved void is required before replacement.');}
 const primary=rules.calculateGas(q.quantity,factor);let market=null;
 if(source.scope==='SCOPE_1'||boundary.scope2_mode==='LOCATION_ONLY'){if(a.market_allocations.length||a.fallback_factor_id)fail(422,'MARKET_NOT_APPLICABLE','Do not apply market instruments to Scope 1 or a location-only boundary.');}
 else {
  const parts=[];for(const allocation of [...a.market_allocations].sort((a,b)=>a.instrumentId.localeCompare(b.instrumentId))){const instrument=await s.get('u_c_instruments',allocation.instrumentId);
   if(instrument.status!=='APPROVED'||instrument.period_id!==period.id||instrument.region!==source.region||instrument.valid_from>a.interval_start||instrument.valid_to<a.interval_end)fail(422,'INSTRUMENT_MISMATCH','Use approved same-period instruments with matching market and complete consumption eligibility dates.');
   const f=await s.get('u_c_factors',instrument.factor_id);rules.checkFactor(a,source,f,['MARKET_CONTRACT']);
   const used=await s.carbonAllocationUsed(instrument.id);if(scaled(used)+scaled(allocation.quantityKwh)>scaled(instrument.quantity_kwh))fail(409,'INSTRUMENT_EXHAUSTED','Allocation exceeds the instrument remaining eligible quantity. Drafts do not reserve instruments.');
   parts.push({...allocation,factor:f,instrument});}
  let fallback=null;if(a.fallback_factor_id){fallback=await s.get('u_c_factors',a.fallback_factor_id);rules.checkFactor(a,source,fallback,['RESIDUAL','GRID_FALLBACK']);reason(a.fallback_reason);if(fallback.use==='GRID_FALLBACK'){const residuals=await s.rows('u_c_factors',{kind:source.kind,substance:source.substance,unit:source.unit,region:source.region,use:'RESIDUAL',status:'APPROVED'},1000);if(residuals.some(f=>f.valid_from<=a.interval_start&&f.valid_to>=a.interval_end))fail(422,'RESIDUAL_AVAILABLE','An approved matching residual-mix factor is registered. Do not silently replace it with the grid-average fallback.');}}
  market=rules.calculateMarket(q.quantity,parts,fallback);
 }
 return {period,boundary,source,factor,quantity:q.quantity,quantityMethod:q,primary,market,evidence};
}
export async function previewRecord(s,b){role(s.user,WRITE);const a=rules.recordInput(b),result=await preflight(s,a);return {...result,persisted:false,instrumentReservation:false};}
async function insertRecord(s,a,check){const r=await s.insert('u_c_records',{...a,boundary_id:check.boundary.id,campus_id:check.source.campus_id,kind:check.source.kind,scope:check.source.scope,unit:check.source.unit,quantity:check.quantity,status:'DRAFT',approved_by:null,created_by:s.user.id});await s.audit('C_RECORD_DRAFTED',r.id,{sourceId:r.source_id,externalKey:r.external_key,quantity:r.quantity});return r;}
export async function createRecord(s,b){role(s.user,WRITE);const a=rules.recordInput(b);await lockPeriod(s,a.period_id);return insertRecord(s,a,await preflight(s,a));}
export async function editRecord(s,rid,b){role(s.user,WRITE);const {version:expected,...input}=b,a=rules.recordInput(input),seen=await s.get('u_c_records',uuid(rid));recordAccess(s,seen);if(a.period_id!==seen.period_id||a.source_id!==seen.source_id||a.replaces_id!==seen.replaces_id)fail(422,'IMMUTABLE_REFERENCE','Keep the original source, period and correction reference.');await lockPeriod(s,a.period_id);const old=await s.get('u_c_records',seen.id,{lock:true});version(old,expected);authorOnly(s.user,old);if(!['DRAFT','REJECTED'].includes(old.status))fail(409,'INVALID_STATE','Only draft or rejected entries can be edited.');const check=await preflight(s,a,{excludeId:old.id});const r=await s.update('u_c_records',old.id,{...a,boundary_id:check.boundary.id,quantity:check.quantity,status:'DRAFT',rejection_reason:null});await s.audit('C_RECORD_EDITED',r.id);return r;}
export async function getRecord(s,rid){const r=await s.get('u_c_records',uuid(rid));recordAccess(s,r);return {...r,calculations:await s.rows('u_c_calculations',{record_id:r.id},1),voids:await s.rows('u_c_voids',{record_id:r.id},100)};}
export async function recordAction(s,rid,action,b){fields(b,['version','reason']);role(s.user,['submit','cancel'].includes(action)?WRITE:REVIEW);const seen=await s.get('u_c_records',uuid(rid));recordAccess(s,seen);await lockPeriod(s,seen.period_id);const old=await s.get('u_c_records',seen.id,{lock:true});version(old,b.version);
 if(['submit','cancel'].includes(action)){authorOnly(s.user,old);if(action==='cancel'){if(!['DRAFT','REJECTED'].includes(old.status))fail(409,'INVALID_STATE','Only unsubmitted drafts or rejected rows can be cancelled.');const r=await s.update('u_c_records',old.id,{status:'CANCELLED',rejection_reason:reason(b.reason)});await s.audit('C_RECORD_CANCELLED',r.id);return r;}
  if(old.status!=='DRAFT')fail(409,'INVALID_STATE','Only a draft can be submitted.');await preflight(s,old,{excludeId:old.id});await s.evidence(old.evidence_ids,true);const r=await s.update('u_c_records',old.id,{status:'SUBMITTED'});await s.audit('C_RECORD_SUBMITTED',r.id);return r;}
 independent(s.user,old);if(old.status!=='SUBMITTED')fail(409,'INVALID_STATE','Only a submitted record can be reviewed.');
 if(action==='reject'){const r=await s.update('u_c_records',old.id,{status:'REJECTED',rejection_reason:reason(b.reason)});await s.audit('C_RECORD_REJECTED',r.id);return r;}
 if(action!=='approve')fail(404,'NOT_FOUND','Unknown record action.');const check=await preflight(s,old,{excludeId:old.id,forApproval:true});if(check.boundary.id!==old.boundary_id)fail(409,'BOUNDARY_CHANGED','Reject and refresh this draft against the new approved boundary.');
 const provenance={schemaVersion:'scope12-1',source:check.source,boundary:{id:check.boundary.id,revision:check.boundary.revision,approach:check.boundary.approach,scope2Mode:check.boundary.scope2_mode,statement:check.boundary.statement},interval:{from:old.interval_start,to:old.interval_end},quantity:check.quantity,quantityInput:old.quantity_input,quantityMethod:check.quantityMethod,factor:check.factor,primary:check.primary,market:check.market,evidence:check.evidence,dataQuality:old.data_quality,assumptions:old.assumptions,zeroReason:old.zero_reason,approvedBy:s.user.id,assurance:'INTERNAL_MAKER_CHECKER_ONLY',notSummable:'LOCATION and MARKET are alternatives; biogenic CO2 is a separate disclosure, not an offset.'};
 const calculation=await s.insert('u_c_calculations',{record_id:old.id,scope1_kg:old.scope==='SCOPE_1'?check.primary.kgCo2e:null,location_kg:old.scope==='SCOPE_2'?check.primary.kgCo2e:null,market_kg:check.market?.kgCo2e??null,biogenic_kg:check.primary.biogenicCo2Kg,provenance});
 for(const a of old.market_allocations)await s.insert('u_c_allocations',{record_id:old.id,instrument_id:a.instrumentId,quantity_kwh:a.quantityKwh});
 const r=await s.update('u_c_records',old.id,{status:'CALCULATED',approved_by:s.user.id});await s.audit('C_RECORD_CALCULATED',r.id,{calculationId:calculation.id,scope1Kg:calculation.scope1_kg,locationKg:calculation.location_kg,marketKg:calculation.market_kg});return {...r,calculation};
}
export async function requestVoid(s,rid,b){role(s.user,WRITE);fields(b,['version','reason']);const seen=await s.get('u_c_records',uuid(rid));recordAccess(s,seen);await lockPeriod(s,seen.period_id);const old=await s.get('u_c_records',seen.id,{lock:true});version(old,b.version);if(old.status!=='CALCULATED')fail(409,'INVALID_STATE','Only calculated entries can be voided.');if(await s.count('u_c_voids',{record_id:old.id,status:['SUBMITTED','APPROVED']}))fail(409,'EXISTING_VOID','An active void already exists.');const r=await s.insert('u_c_voids',{period_id:old.period_id,record_id:old.id,reason:reason(b.reason),status:'SUBMITTED',approved_by:null,created_by:s.user.id});await s.audit('C_VOID_REQUESTED',r.id,{recordId:old.id});return r;}
export async function reviewVoid(s,rid,action,b){role(s.user,REVIEW);fields(b,['version','reason']);const seen=await s.get('u_c_voids',uuid(rid)),record=await s.get('u_c_records',seen.record_id);await lockPeriod(s,record.period_id);const old=await s.get('u_c_voids',seen.id,{lock:true});version(old,b.version);independent(s.user,old);if(old.status!=='SUBMITTED')fail(409,'INVALID_STATE','Void is not pending.');choice(action,['approve','reject'],'action');const r=await s.update('u_c_voids',old.id,{status:action==='approve'?'APPROVED':'REJECTED',approved_by:action==='approve'?s.user.id:null,rejection_reason:action==='reject'?reason(b.reason):null});await s.audit('C_VOID_'+r.status,r.id,{recordId:record.id,allocationEffect:action==='approve'?'Released for this same reporting period only':'No release'});return r;}
export async function createAction(s,b){role(s.user,['ADMIN','ENTRY','REVIEWER']);fields(b,['periodId','campusId','sourceId','title','severity','ownerId','dueDate','description','evidenceIds']);await lockPeriod(s,uuid(b.periodId));await s.location(uuid(b.campusId));await s.userRef(uuid(b.ownerId),['ADMIN','ENTRY','REVIEWER']);if(b.sourceId){const source=await s.get('u_c_sources',uuid(b.sourceId));if(source.campus_id!==b.campusId)fail(422,'SOURCE_CAMPUS','Source and action campus differ.');await sourceAccess(s,source);}const evidence=evidenceIds(b.evidenceIds);await s.evidence(evidence,false);
 const r=await s.insert('u_c_actions',{period_id:b.periodId,campus_id:b.campusId,source_id:b.sourceId||null,title:text(b.title,'title',180),severity:choice(b.severity,['LOW','MEDIUM','HIGH','CRITICAL'],'severity'),owner_id:b.ownerId,due_date:day(b.dueDate),description:reason(b.description),evidence_ids:evidence,status:'OPEN',created_by:s.user.id});await s.audit('C_ACTION_CREATED',r.id);return r;}
export async function actionTransition(s,rid,action,b){role(s.user,action==='resolve'?['ADMIN','ENTRY','REVIEWER']:REVIEW);fields(b,['version','reason','evidenceIds']);const seen=await s.get('u_c_actions',uuid(rid));await lockPeriod(s,seen.period_id);const old=await s.get('u_c_actions',seen.id,{lock:true});version(old,b.version);const why=reason(b.reason);let values;
 if(action==='resolve'){if(s.user.id!==old.owner_id&&s.user.role!=='ADMIN')fail(403,'OWNER_REQUIRED','Only the assigned owner or administrator can resolve this action.');if(old.status!=='OPEN')fail(409,'INVALID_STATE','Only an open action can be resolved.');const ids=evidenceIds(b.evidenceIds);await s.evidence(ids,true);values={status:'RESOLVED',resolution:why,resolved_by:s.user.id,evidence_ids:ids};}
 else if(action==='close'){if(old.status!=='RESOLVED')fail(409,'INVALID_STATE','Resolve the action with evidence before closing it.');if(old.resolved_by===s.user.id)fail(403,'SELF_APPROVAL','A different reviewer must close the corrective action.');await s.evidence(old.evidence_ids,true);values={status:'CLOSED',closed_by:s.user.id};}
 else if(action==='reopen'){if(old.status==='OPEN')fail(409,'INVALID_STATE','Action is already open.');values={status:'OPEN',closed_by:null,resolved_by:null};}
 else fail(404,'NOT_FOUND','Unknown action transition.');const r=await s.update('u_c_actions',old.id,values);await s.audit('C_ACTION_'+r.status,r.id,{reason:why});return r;}
export async function importRecords(s,b,{commit=false}={}){role(s.user,WRITE);fields(b,['csv']);const rows=csvParse(b.csv),prepared=[],errors=[];
 for(const [i,row] of rows.entries()){try{fields(row,['periodId','sourceId','intervalStart','intervalEnd','externalKey','description','quantity','unit','factorId','fallbackFactorId','fallbackReason','evidenceIds','dataQuality','assumptions','zeroReason']);const {quantity,unit,...rest}=row;const body={...rest,quantityInput:{mode:'DIRECT',quantity,unit},evidenceIds:row.evidenceIds?row.evidenceIds.split('|'):[]};for(const k of ['fallbackFactorId','fallbackReason','assumptions','zeroReason'])if(body[k]==='')delete body[k];const a=rules.recordInput(body);
   if(prepared.some(p=>p.a.external_key===a.external_key||p.a.source_id===a.source_id&&overlaps(p.a,a)))fail(409,'CSV_OVERLAP','Repeated source key or overlapping source intervals within this CSV.');
   if(prepared.length&&prepared[0].a.period_id!==a.period_id)fail(422,'CSV_PERIOD','Use one reporting period per atomic CSV import.');if(commit)await lockPeriod(s,a.period_id);const check=await preflight(s,a);prepared.push({a,check});
  }catch(e){if(!e.status)throw e;errors.push({line:i+2,code:e.code,message:e.message});}}
 if(errors.length){if(commit)fail(422,'IMPORT_REJECTED','No records imported; fix every invalid row.',{errors});return {valid:false,errors,imported:0};}
 if(!commit)return {valid:true,rows:prepared.length,preview:prepared.map(({a,check})=>({externalKey:a.external_key,quantity:check.quantity,unit:check.source.unit})),imported:0,note:'Direct-quantity CSV drafts only; split certificate allocations use the JSON API. Preview does not reserve source intervals or instruments.'};
 const items=[];for(const {a,check} of prepared)items.push(await insertRecord(s,a,check));return {valid:true,atomic:true,imported:items.length,items};}
