Foreground yes
LogTime yes
LogClean no
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
FixStaleSocket yes
MaxThreads 4
MaxQueue 20
StreamMaxLength 12M
MaxFileSize 12M
MaxScanSize 50M
MaxRecursion 10
MaxFiles 1000
MaxScanTime 30000
AlertExceedsMax yes
AlertEncrypted yes
ScanPDF yes
ScanArchive yes
ReadTimeout 60
CommandReadTimeout 30
