/** Domain workflow tests use a clearly labelled in-memory repository, not a PostgreSQL emulator. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { id } from '../../src/core.mjs';
import * as collect from '../../src/university/collection.mjs';
import * as emit from '../../src/university/emissions.mjs';
import * as collab from '../../src/university/collaboration.mjs';
import * as reports from '../../src/university/reporting.mjs';
import * as plan from '../../src/university/planning.mjs';
import { csvWrite,hash } from '../../src/university/core.mjs';
import { fixture,factorBody,emissionBody } from './memory-store.mjs';
const reject=(fn,code)=>assert.rejects(fn,e=>e.code===code);
async function approvedFactor(f,extra={}){let r=await emit.createFactor(f.s,{...factorBody,...extra});r=await emit.approveFactor(f.s.for(f.actors.REVIEWER),r.id,{version:r.version});return r;}
async function screened(f,n=1){return emit.setScreening(f.s,{periodId:f.period,categoryNumber:n,decision:'INCLUDED',rationale:'Explicit synthetic test boundary, not actual university data'});}
async function calculated(f,extra={}){const factor=await approvedFactor(f,{...(extra.category?{category:extra.category}:{}),...(extra.unit?{unit:extra.unit}:{}),versionLabel:'TEST-'+id()});if(factor.category==='PURCHASED_GOODS')await screened(f).catch(e=>{if(e.code!=='STALE_VERSION')throw e;});let e=await emit.createEmission(f.s.for(f.actors.ENTRY),emissionBody(f,factor.id,extra));e=await emit.emissionAction(f.s.for(f.actors.ENTRY),e.id,'submit',{version:e.version});e=await emit.emissionAction(f.s.for(f.actors.REVIEWER),e.id,'approve',{version:e.version});return e;}
async function waterTask(f,extra={}){let k=(await f.s.rows('u_kpis',{code:'WATER_WITHDRAWAL_M3'}))[0];if(!k){await collect.installCatalog(f.s,{});k=(await f.s.rows('u_kpis',{code:'WATER_WITHDRAWAL_M3'}))[0];}return collect.createTask(f.s,{periodId:f.period,campusId:f.campus,kpiId:k.id,assigneeId:f.actors.ENTRY.id,reviewerId:f.actors.REVIEWER.id,bucket:'METER_A',intervalStart:'2026-04-01',intervalEnd:'2026-04-30',dueDate:'2026-05-10',...extra});}
async function approveMetric(f,t,value='12'){let sub=await collect.createSubmission(f.s.for(f.actors.ENTRY),t.id,{taskVersion:t.version,value,unit:'m3',evidenceIds:[f.document.id]});sub=await collect.submissionAction(f.s.for(f.actors.ENTRY),sub.id,'submit',{version:sub.version});return collect.submissionAction(f.s.for(f.actors.REVIEWER),sub.id,'approve',{version:sub.version});}
function lockPeriod(f){const p=f.state.tables.periods.find(p=>p.id===f.period);p.status='LOCKED';p.version++;}
async function approvedReport(f,title='Test baseline'){lockPeriod(f);let r=await reports.createReport(f.s,{periodId:f.period,title,purpose:'UNIVERSITY_SUSTAINABILITY',boundaryStatement:'Same synthetic test university operational boundary'});return reports.reviewReport(f.s.for(f.actors.REVIEWER),r.id,'approve',{version:r.version});}
test('installing university catalog is repeatable and never seeds measurements or factors',async()=>{const f=fixture();const a=await collect.installCatalog(f.s,{}),b=await collect.installCatalog(f.s,{});assert.equal(a.added,22);assert.equal(b.added,0);assert.equal(await f.s.count('u_submissions'),0);assert.equal(await f.s.count('u_factors'),0);});
test('department cannot reference another university campus',async()=>{const f=fixture();await reject(()=>collect.createDepartment(f.s,{campusId:id(),name:'Lab',code:'LAB',ownerId:f.actors.ENTRY.id}),'NOT_FOUND');});
test('collection rejects overlapping intervals for the same KPI source',async()=>{const f=fixture();await waterTask(f);await reject(()=>waterTask(f,{intervalStart:'2026-04-15',intervalEnd:'2026-05-15',dueDate:'2026-05-20'}),'OVERLAPPING_TASK');assert.ok(f.state.locks.length>=2);});
test('normalization task must use one whole-period campus-wide bucket',async()=>{const f=fixture();await collect.installCatalog(f.s,{});const k=(await f.s.rows('u_kpis',{code:'STUDENT_FTE'}))[0];await reject(()=>waterTask(f,{kpiId:k.id}),'NORMALIZATION_BOUNDARY');});
test('data-entry users cannot read or write another assignee task',async()=>{const f=fixture(),t=await waterTask(f);await reject(()=>collect.getTask(f.s.for(f.actors.OTHER_ENTRY),t.id),'NOT_FOUND');await reject(()=>collect.createSubmission(f.s.for(f.actors.OTHER_ENTRY),t.id,{taskVersion:t.version,value:'1',unit:'m3'}),'NOT_FOUND');});
test('KPI approval creates a snapshot and completes the task',async()=>{const f=fixture(),t=await waterTask(f),sub=await approveMetric(f,t);assert.equal(sub.status,'APPROVED');assert.equal((await f.s.get('u_tasks',t.id)).status,'COMPLETE');assert.equal((await f.s.metricRows(f.period))[0].value,'12.000000');});
test('KPI cannot be submitted without required clean evidence',async()=>{const f=fixture(),t=await waterTask(f),sub=await collect.createSubmission(f.s.for(f.actors.ENTRY),t.id,{taskVersion:t.version,value:'1',unit:'m3'});await reject(()=>collect.submissionAction(f.s.for(f.actors.ENTRY),sub.id,'submit',{version:sub.version}),'EVIDENCE_REQUIRED');});
test('quarantined document cannot be used as evidence',async()=>{const f=fixture(),t=await waterTask(f);f.state.tables.documents[0].scan_result='INFECTED';await reject(()=>collect.createSubmission(f.s.for(f.actors.ENTRY),t.id,{taskVersion:t.version,value:'1',unit:'m3',evidenceIds:[f.document.id]}),'EVIDENCE_NOT_READY');});
test('another administrator may not edit an author draft and then approve it',async()=>{const f=fixture(),t=await waterTask(f),sub=await collect.createSubmission(f.s.for(f.actors.ENTRY),t.id,{taskVersion:t.version,value:'1',unit:'m3'});await reject(()=>collect.editSubmission(f.s,sub.id,{version:sub.version,value:'2',unit:'m3'}),'AUTHOR_REQUIRED');});
test('maker-checker prevents self-approval even after elevation to administrator',async()=>{const f=fixture(),t=await waterTask(f);let sub=await collect.createSubmission(f.s.for(f.actors.ENTRY),t.id,{taskVersion:t.version,value:'1',unit:'m3',evidenceIds:[f.document.id]});sub=await collect.submissionAction(f.s.for(f.actors.ENTRY),sub.id,'submit',{version:sub.version});await reject(()=>collect.submissionAction(f.s.for({...f.actors.ENTRY,role:'ADMIN'}),sub.id,'approve',{version:sub.version}),'SELF_APPROVAL');});
test('KPI correction preserves old snapshot and counts only the latest approved revision',async()=>{const f=fixture(),t=await waterTask(f);await approveMetric(f,t,'10');const current=await f.s.get('u_tasks',t.id);let sub=await collect.createSubmission(f.s.for(f.actors.ENTRY),t.id,{taskVersion:current.version,value:'15',unit:'m3',evidenceIds:[f.document.id],correctionReason:'Meter transcription corrected against actual evidence'});sub=await collect.submissionAction(f.s.for(f.actors.ENTRY),sub.id,'submit',{version:sub.version});await collect.submissionAction(f.s.for(f.actors.REVIEWER),sub.id,'approve',{version:sub.version});assert.equal(await f.s.count('u_metric_snapshots'),2);assert.equal(reports.metricSummary(await f.s.metricRows(f.period))[0].value,'15.000000');});
test('KPI waiver records a reason and cannot hide already approved data',async()=>{const f=fixture(),t=await waterTask(f);const r=await collect.waiveTask(f.s,t.id,{version:t.version,reason:'Meter not commissioned during the reporting interval'});assert.equal(r.status,'WAIVED');await reject(()=>collect.createSubmission(f.s.for(f.actors.ENTRY),r.id,{taskVersion:r.version,value:'1',unit:'m3'}),'TASK_WAIVED');});
test('factor author cannot approve their own factor',async()=>{const f=fixture(),r=await emit.createFactor(f.s,factorBody);await reject(()=>emit.approveFactor(f.s,r.id,{version:r.version}),'SELF_APPROVAL');});
test('Scope 3 approval requires declared included category and evidence',async()=>{const f=fixture(),factor=await approvedFactor(f);let e=await emit.createEmission(f.s.for(f.actors.ENTRY),emissionBody(f,factor.id));e=await emit.emissionAction(f.s.for(f.actors.ENTRY),e.id,'submit',{version:e.version});await reject(()=>emit.emissionAction(f.s.for(f.actors.REVIEWER),e.id,'approve',{version:e.version}),'SCOPE3_SCREENING');});
test('calculated emission retains exact factor provenance and evidence hash',async()=>{const f=fixture(),e=await calculated(f);assert.equal(e.calculation.kg_co2e,'150.000000');assert.equal(e.calculation.provenance.evidence[0].sha256,'a'.repeat(64));assert.match(e.calculation.provenance.factor.source,/SYNTHETIC/);});
test('repeat approval cannot create a second calculation',async()=>{const f=fixture(),e=await calculated(f);await reject(()=>emit.emissionAction(f.s.for(f.actors.REVIEWER),e.id,'approve',{version:e.version}),'INVALID_STATE');assert.equal(await f.s.count('u_calculations'),1);});
test('a category with calculated emissions cannot be excluded',async()=>{const f=fixture();await calculated(f);const old=(await f.s.rows('u_scope3_screenings'))[0];await reject(()=>emit.setScreening(f.s,{periodId:f.period,categoryNumber:1,decision:'EXCLUDED',rationale:'Trying to hide already recorded emissions',version:old.version}),'CATEGORY_HAS_CALCULATIONS');});
test('data-entry emission read is author-scoped',async()=>{const f=fixture(),e=await calculated(f);await reject(()=>emit.getEmission(f.s.for(f.actors.OTHER_ENTRY),e.id),'NOT_FOUND');});
test('locked periods reject new university activity records',async()=>{const f=fixture(),factor=await approvedFactor(f);lockPeriod(f);await reject(()=>emit.createEmission(f.s.for(f.actors.ENTRY),emissionBody(f,factor.id)),'PERIOD_LOCKED');});
test('approved void excludes a calculation without deleting the historical ledger',async()=>{const f=fixture(),e=await calculated(f);const v=await emit.requestVoid(f.s.for(f.actors.ENTRY),e.id,{version:e.version,reason:'Duplicate procurement boundary detected during review'});await emit.reviewVoid(f.s.for(f.actors.REVIEWER),v.id,'approve',{version:v.version});assert.equal((await f.s.inventory(f.period)).length,0);assert.equal(await f.s.count('u_calculations'),1);});
test('replacement activity requires an approved void',async()=>{const f=fixture(),e=await calculated(f);await reject(()=>emit.createEmission(f.s.for(f.actors.ENTRY),emissionBody(f,e.factor_id,{replacesId:e.id})),'VOID_REQUIRED');});
test('CSV preview validates fields and references without adding records',async()=>{const f=fixture(),factor=await approvedFactor(f),b=emissionBody(f,factor.id),header=Object.keys(b),csv=csvWrite(header,[header.map(k=>k==='evidenceIds'?b[k].join('|'):b[k])]);const r=await emit.importEmissions(f.s.for(f.actors.ENTRY),{csv});assert.equal(r.valid,true);assert.equal(await f.s.count('u_emissions'),0);});
test('CSV commit inserts drafts atomically and rejects malformed batches before writing',async()=>{const f=fixture(),factor=await approvedFactor(f),a=emissionBody(f,factor.id),b=emissionBody(f,factor.id,{quantity:'wrong'}),header=Object.keys(a),csv=csvWrite(header,[a,b].map(row=>header.map(k=>k==='evidenceIds'?row[k].join('|'):row[k])));await reject(()=>f.s.transaction(()=>emit.importEmissions(f.s.for(f.actors.ENTRY),{csv},{commit:true})),'IMPORT_REJECTED');assert.equal(await f.s.count('u_emissions'),0);});
test('overview combines original core ledger and new carbon records, but not student supplemental emissions',async()=>{const f=fixture();await calculated(f);await calculated(f,{category:'STUDENT_COMMUTING',unit:'passenger_km',quantity:'1000'});f.state.coreInventory.push({id:id(),record_id:id(),tenant_id:f.tenant,period_id:f.period,campus_id:f.campus,activity_date:'2026-04-01',category:'PURCHASED_ELECTRICITY',scope:'SCOPE_2',scope3_category:null,quantity:'100',unit:'kWh',kg_co2e:'71.000000',ledger:'CORE',evidence_count:0});const o=await reports.overview(f.s,f.period);assert.equal(o.inventory.totalKgCo2e,'221.000000');assert.equal(o.inventory.scopes.SUPPLEMENTAL,'1500.000000');});
test('report snapshots require locked periods and an independent approver',async()=>{const f=fixture();await calculated(f);const b={periodId:f.period,title:'Report',purpose:'INVENTORY_EVIDENCE',boundaryStatement:'Synthetic test boundary declaration'};await reject(()=>reports.createReport(f.s,b),'PERIOD_MUST_BE_LOCKED');lockPeriod(f);const r=await reports.createReport(f.s,b);await reject(()=>reports.reviewReport(f.s,r.id,'approve',{version:r.version}),'SELF_APPROVAL');});
test('period reopening invalidates approval of a stale report snapshot',async()=>{const f=fixture();await calculated(f);lockPeriod(f);const r=await reports.createReport(f.s,{periodId:f.period,title:'Report',purpose:'INVENTORY_EVIDENCE',boundaryStatement:'Synthetic test boundary declaration'});f.state.tables.periods[0].version++;await reject(()=>reports.reviewReport(f.s.for(f.actors.REVIEWER),r.id,'approve',{version:r.version}),'STALE_REPORT');});
test('approved reports export frozen JSON, CSV and escaped print-ready HTML',async()=>{const f=fixture();await calculated(f);const r=await approvedReport(f,'<script>bad()</script>');for(const format of ['json','csv','html']){const file=await reports.exportReport(f.s,r.id,format);assert.ok(file.bytes.length);assert.ok(file.name.endsWith('.'+format));if(format==='html'){assert.ok(!file.bytes.includes('<script>'));assert.match(file.bytes,/&lt;script&gt;/);}}});
test('snapshot corruption is detected before exporting',async()=>{const f=fixture();await calculated(f);const r=await approvedReport(f);f.state.tables.u_reports[0].snapshot.boundaryStatement='Tampered content';await reject(()=>reports.exportReport(f.s,r.id,'json'),'INTEGRITY_ERROR');});
test('facts endpoint carries real record IDs and does not pretend to be AI',async()=>{const f=fixture(),e=await calculated(f),out=await reports.insights(f.s,{periodId:f.period,questionId:'EMISSIONS_SUMMARY'});assert.equal(out.engine,'DETERMINISTIC_SQL_NOT_LLM');assert.equal(out.citations[0].recordId,e.id);assert.equal(out.facts.totalKgCo2e,'150.000000');});
async function supplier(f){const vendor=await collab.createSupplier(f.s,{name:'Synthetic vendor',code:'TEST',contactEmail:'supplier@example.invalid',category:'FOOD'});return collab.createSupplierRequest(f.s,{supplierId:vendor.id,periodId:f.period,title:'Supplier water questionnaire',dueDate:'2026-12-01',questions:[{key:'WATER',label:'Water consumption',type:'NUMBER',required:true,unit:'m3'}]});}
test('supplier capability is stored hashed, returned once and can access only its questionnaire',async()=>{const f=fixture(),r=await supplier(f),inv=await collab.issueInvite(f.s,'SUPPLIER',r.id,{version:r.version,expiresInDays:7}),stored=(await f.s.rows('u_invites'))[0];assert.equal(stored.token_hash,hash(inv.token));assert.ok(!JSON.stringify(stored).includes(inv.token));const parsed=collab.parseCapability('Capability '+inv.token),out=await collab.portal(f.s.for({tenant_id:f.tenant,id:null,role:'CAPABILITY'}),parsed);assert.equal(out.questions.length,1);assert.equal(out.id,r.id);assert.ok(!('tenant_id' in out));});
test('supplier response is single-use, needs evidence and separate internal approval, and does not post emissions',async()=>{const f=fixture(),r=await supplier(f),inv=await collab.issueInvite(f.s,'SUPPLIER',r.id,{version:r.version,expiresInDays:7}),parsed=collab.parseCapability('Capability '+inv.token),external=f.s.for({tenant_id:f.tenant,id:null,role:'CAPABILITY'});await collab.portal(external,parsed,{version:inv.requestVersion,answers:{WATER:'250'},attestation:true});await reject(()=>collab.portal(external,parsed,{version:inv.requestVersion,answers:{WATER:'250'},attestation:true}),'CAPABILITY_USED');let current=await f.s.get('u_supplier_requests',r.id);await reject(()=>collab.reviewSupplier(f.s.for(f.actors.REVIEWER),r.id,'approve',{version:current.version}),'EVIDENCE_REQUIRED');current=await collab.supplierEvidence(f.s,r.id,{version:current.version,evidenceIds:[f.document.id]});current=await collab.reviewSupplier(f.s.for(f.actors.REVIEWER),r.id,'approve',{version:current.version});assert.equal(current.status,'APPROVED');assert.equal(await f.s.count('u_emissions'),0);});
test('revoked or expired capability cannot be used',async()=>{const f=fixture(),r=await supplier(f),inv=await collab.issueInvite(f.s,'SUPPLIER',r.id,{version:r.version,expiresInDays:7});await collab.revokeInvite(f.s,inv.id,{reason:'Supplier contact changed, capability no longer needed'});await reject(()=>collab.portal(f.s,collab.parseCapability('Capability '+inv.token)),'INVALID_CAPABILITY');});
test('full materiality flow gathers consented anonymous responses and publishes only aggregates',async()=>{const f=fixture();let a=await collab.createMateriality(f.s,{periodId:f.period,title:'Campus priorities',topics:[{code:'WATER',label:'Water stewardship'}],impactThreshold:'3',financialThreshold:'3',minResponses:5});for(let n=0;n<5;n++){const inv=await collab.issueInvite(f.s,'MATERIALITY',a.id,{version:a.version,expiresInDays:7,stakeholderGroup:'STUDENTS'});await collab.portal(f.s.for({tenant_id:f.tenant,id:null,role:'CAPABILITY'}),collab.parseCapability('Capability '+inv.token),{version:a.version,consent:true,scores:[{topic:'WATER',impact:4,financial:2,rationale:'Private respondent explanation'}]});}a=await collab.materialityAction(f.s,a.id,'close',{version:a.version});a=await collab.materialityAction(f.s.for(f.actors.REVIEWER),a.id,'approve',{version:a.version});assert.equal(a.snapshot.responseCount,5);assert.equal(a.snapshot.topics[0].impact,'4.00');assert.ok(!JSON.stringify(a.snapshot).includes('Private respondent'));});
test('materiality publication refuses inadequate response numbers',async()=>{const f=fixture();let a=await collab.createMateriality(f.s,{periodId:f.period,title:'Campus priorities',topics:[{code:'WATER',label:'Water'}],impactThreshold:'3',financialThreshold:'3',minResponses:5});a=await collab.materialityAction(f.s,a.id,'close',{version:a.version});await reject(()=>collab.materialityAction(f.s.for(f.actors.REVIEWER),a.id,'approve',{version:a.version}),'INSUFFICIENT_RESPONSES');});
test('targets use a frozen approved baseline and planned initiatives never deduct emissions',async()=>{const f=fixture();await calculated(f);const report=await approvedReport(f),target=await plan.createTarget(f.s,{name:'Recorded reduction target',baselineReportId:report.id,scopes:['SCOPE_3'],reductionPercent:'20',targetDate:'2030-03-31',ownerId:f.actors.ENTRY.id});assert.equal(target.baseline_kg,'150.000000');const initiative=await plan.createInitiative(f.s,{targetId:target.id,campusId:f.campus,name:'Supplier engagement',ownerId:f.actors.ENTRY.id,startDate:'2027-04-01',endDate:'2028-03-31',estimatedReductionKg:'500',investmentInr:'1000',annualSavingsInr:'100',assumptions:'Synthetic planning assumption; no verified savings'});assert.equal(initiative.inventoryDeduction,false);assert.equal(reports.inventorySummary(await f.s.inventory(f.period)).totalKgCo2e,'150.000000');const p=await plan.targetProgress(f.s,target.id,report.id);assert.equal(p.comparable,false);assert.equal(p.observedReductionPercent,null);});
test('PCF preview and approval remain outside the emissions ledger',async()=>{const f=fixture(),factor=await approvedFactor(f),b={name:'Test campus meal',functionalUnit:'one meal',outputQuantity:'100',boundary:'Synthetic screening only, ingredients stage',studyDate:'2026-06-01',bom:[{name:'Ingredient',stage:'MATERIALS',quantity:'10',unit:'kg',factorId:factor.id,allocationPercent:'100'}]};let pcf=await plan.createPcf(f.s.for(f.actors.ENTRY),b);pcf=await plan.pcfAction(f.s.for(f.actors.ENTRY),pcf.id,'submit',{version:pcf.version});pcf=await plan.pcfAction(f.s.for(f.actors.REVIEWER),pcf.id,'approve',{version:pcf.version});assert.equal(pcf.result.perFunctionalUnitKgCo2e,'0.150000');assert.equal((await f.s.inventory(f.period)).length,0);});
