import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import * as c from '../src/core.mjs';
import { config } from '../src/config.mjs';
import { validateUpload } from '../src/storage.mjs';
import { parseInvoiceText } from '../src/invoice-text.mjs';
import { extractBounded } from '../src/scanner.mjs';
import { Metrics } from '../src/metrics.mjs';
const tenant = '11111111-1111-4111-8111-111111111111', other = '22222222-2222-4222-8222-222222222222';
const base = { periodId: tenant, campusId: other, category: 'PURCHASED_ELECTRICITY', unit: 'kWh', quantity: '12500', activityDate: '2026-09-01' };
const env = { DATABASE_URL: 'postgres://cs_api:p@localhost/db', WORKER_DATABASE_URL: 'postgres://cs_worker:p@localhost/db', ALLOWED_ORIGINS: 'http://localhost:8080', S3_BUCKET: 'evidence', METRICS_TOKEN: 'm'.repeat(40), REQUEST_HASH_SECRET: 'r'.repeat(40) };
const throws = (fn, code) => assert.throws(fn, e => e.code === code);
test('canonical request hashing ignores JSON key ordering', () => assert.equal(c.canonical({ b: 2, a: 1 }), c.canonical({ a: 1, b: 2 })));
test('decimal strings normalize without binary floating point', () => assert.equal(c.decimal('0.1'), '0.100000'));
for (const value of [1, '1e3', '-1', '01', '1.0000001', 'NaN', 'Infinity', '0', '1000000000000'])
    test(`reject invalid consumption ${JSON.stringify(value)}`, () => throws(() => c.decimal(value), 'INVALID_DECIMAL'));
test('zero money is allowed while zero consumption is not', () => assert.equal(c.decimal('0', 'money', 2, true), '0.00'));
test('exact multiplication keeps decimal result', () => assert.equal(c.multiplyDecimals('0.1', '0.2'), '0.020000'));
test('rounding half-up to six decimal places', () => assert.equal(c.multiplyDecimals('1', '0.000000500'), '0.000001'));
test('large products do not use JS safe-integer arithmetic', () => assert.equal(c.multiplyDecimals('999999999999', '1.000000001'), '1000000000999.000000'));
test('strict dates reject February overflow', () => throws(() => c.day('2026-02-30'), 'INVALID_DATE'));
test('leap date accepted', () => assert.equal(c.day('2028-02-29'), '2028-02-29'));
test('activity scope is derived from category', () => assert.equal(c.activityInput(base).scope, 'SCOPE_2'));
test('money cannot replace a consumption quantity', () => throws(() => c.activityInput({ ...base, quantity: undefined, amountInr: '1200' }), 'INVALID_DECIMAL'));
test('canonical unit mismatch rejected', () => throws(() => c.activityInput({ ...base, unit: 'INR' }), 'UNIT_MISMATCH'));
test('caller cannot select a tenant in an activity payload', () => throws(() => c.activityInput({ ...base, tenantId: other }), 'SERVER_OWNED_FIELD'));
test('caller cannot override the accounting scope', () => throws(() => c.activityInput({ ...base, scope: 'SCOPE_1' }), 'SERVER_OWNED_FIELD'));
test('semantic duplicate fingerprint is independent of description', () => assert.equal(c.fingerprint(c.activityInput(base)), c.fingerprint(c.activityInput({ ...base, description: 'Changed wording' }))));
test('duplicate override requires a substantive reason', () => throws(() => c.activityInput({ ...base, duplicateReason: 'yes' }), 'DUPLICATE_REASON'));
test('creator may submit own draft', () => assert.equal(c.workflow({ version: 1, status: 'DRAFT', created_by: tenant }, 'submit', { id: tenant, role: 'ENTRY' }, { version: 1 }).status, 'SUBMITTED'));
test('other data-entry user cannot submit', () => throws(() => c.workflow({ version: 1, status: 'DRAFT', created_by: tenant }, 'submit', { id: other, role: 'ENTRY' }, { version: 1 }), 'NOT_OWNER'));
test('leadership cannot approve', () => throws(() => c.workflow({ version: 1, status: 'UNDER_REVIEW', created_by: tenant }, 'verify', { id: other, role: 'LEADERSHIP' }, { version: 1 }), 'FORBIDDEN'));
test('admin cannot self-approve', () => throws(() => c.workflow({ version: 1, status: 'UNDER_REVIEW', created_by: tenant }, 'verify', { id: tenant, role: 'ADMIN' }, { version: 1 }), 'SELF_APPROVAL'));
test('separate reviewer can verify', () => assert.equal(c.workflow({ version: 1, status: 'UNDER_REVIEW', created_by: tenant }, 'verify', { id: other, role: 'REVIEWER' }, { version: 1 }).status, 'VERIFIED'));
test('stale writes are rejected before state mutation', () => throws(() => c.workflow({ version: 2, status: 'DRAFT', created_by: tenant }, 'submit', { id: tenant, role: 'ENTRY' }, { version: 1 }), 'STALE_VERSION'));
test('cannot skip review', () => throws(() => c.workflow({ version: 1, status: 'DRAFT', created_by: tenant }, 'verify', { id: other, role: 'REVIEWER' }, { version: 1 }), 'INVALID_STATE'));
test('reject requires reason', () => throws(() => c.workflow({ version: 1, status: 'SUBMITTED' }, 'reject', { role: 'REVIEWER' }, { version: 1, reason: 'no' }), 'REASON_REQUIRED'));
test('keyset cursor round-trip preserves timestamp and UUID', () => { const rows = [{ id: tenant, created_at: '2026-09-01T00:00:00.123Z' }, { id: other, created_at: '2026-09-01T00:00:00.122Z' }]; const p = c.page(rows, 1); assert.deepEqual(c.pagination({ cursor: p.nextCursor, limit: '1' }).cursor, [rows[0].created_at, tenant]); });
test('invalid cursors rejected', () => throws(() => c.pagination({ cursor: 'bad' }), 'INVALID_CURSOR'));
test('list requests cannot bypass the page cap', () => throws(() => c.pagination({ limit: '10000' }), 'INVALID_LIMIT'));
test('session tokens use random secrets and tenant-scoped hashes', () => { const a = c.sessionToken(tenant), b = c.sessionToken(tenant); assert.notEqual(a, b); assert.deepEqual(c.parseToken('Bearer ' + a), { tenantId: tenant, tokenHash: c.hash(a) }); });
test('malformed bearer rejected', () => throws(() => c.parseToken('Bearer abc'), 'UNAUTHENTICATED'));
test('password hashing uses async scrypt and verifies without plaintext storage', async () => { const h = await c.passwordHash('ExampleTest!LongPassword'); assert(!h.includes('ExampleTest')); assert(await c.passwordVerify('ExampleTest!LongPassword', h)); assert(!await c.passwordVerify('WrongPassword!', h)); });
test('short passwords rejected', async () => assert.rejects(c.passwordHash('short'), e => e.code === 'PASSWORD_POLICY'));
test('weak idempotency key rejected', () => throws(() => c.idempotencyKey('x'), 'IDEMPOTENCY_REQUIRED'));
test('internal errors never expose database messages', () => { const r = c.errorResponse(Error('postgres://secret/password SELECT sql'), 'request-1'); assert.equal(r.status, 500); assert(!JSON.stringify(r).includes('secret')); });
test('unique conflict has a safe machine-readable error', () => assert.equal(c.errorResponse({ code: '23505', detail: 'sensitive' }, 'req').status, 409));
test('default config is bounded and development only', () => { const cfg = config(env); assert.equal(cfg.production, false); assert.equal(cfg.maxUploads, 4); assert.equal(cfg.poolMax, 10); });
test('production rejects insecure database transport', () => assert.throws(() => config({ ...env, NODE_ENV: 'production' }), /DB_SSL/));
test('production rejects HTTP browser origins', () => assert.throws(() => config({ ...env, NODE_ENV: 'production', DB_SSL: 'true' }), /HTTPS/));
test('database URL cannot override TLS verification', () => assert.throws(() => config({ ...env, DATABASE_URL: env.DATABASE_URL + '?sslmode=no-verify' }), /sslmode/));
test('pool size has a hard bound', () => assert.throws(() => config({ ...env, DB_POOL_MAX: '1000' }), /DB_POOL_MAX/));
test('request digest secret is mandatory', () => assert.throws(() => config({ ...env, REQUEST_HASH_SECRET: '' }), /REQUEST_HASH_SECRET/));
test('file type uses bytes, not just extension', () => throws(() => validateUpload('invoice.pdf', 'application/pdf', Buffer.from('not PDF')), 'UNSUPPORTED_FILE'));
test('MIME spoof is rejected', () => throws(() => validateUpload('invoice.txt', 'image/png', Buffer.from('hello')), 'MIME_MISMATCH'));
test('filename cannot escape a directory', () => assert.equal(validateUpload('../../invoice.txt', 'text/plain', Buffer.from('hello')).name, 'invoice.txt'));
test('HTML and executable files are not accepted', () => throws(() => validateUpload('invoice.html', 'text/html', Buffer.from('<script>')), 'UNSUPPORTED_FILE'));
test('empty upload rejected', () => throws(() => validateUpload('invoice.txt', 'text/plain', Buffer.alloc(0)), 'EMPTY_FILE'));
test('upload size cap enforced', () => throws(() => validateUpload('invoice.txt', 'text/plain', Buffer.alloc(11), 10), 'FILE_TOO_LARGE'));
test('extraction never converts money into consumption', () => assert.equal(parseInvoiceText('Total amount: INR 12000').fields.quantity, undefined));
test('MWh is explicitly normalized to kWh with a warning', () => { const x = parseInvoiceText('Consumption: 2 MWh'); assert.equal(x.fields.quantity, 2000); assert(x.warnings.some(x => x.includes('converted'))); });
test('ambiguous invoice consumption lines force manual review', () => assert.equal(parseInvoiceText('Consumption: 2 kWh\nConsumption: 3 kWh').fields.quantity, undefined));
test('bounded extraction executes real text parsing in a worker thread', async () => { const x = await extractBounded(Buffer.from('Vendor: Test Supplier\nInvoice No: T-100\nConsumption: 100 kWh\nTotal amount: INR 950'), 'text/plain'); assert.equal(x.fields.quantity, 100); assert.equal(x.fields.amountInr, 950); assert.equal(x.ocrAvailable, false); });
test('real sample PDF parser is retained and works within the bounded worker', async () => { const b = await readFile(new URL('../samples/sample-electricity.pdf', import.meta.url)); const x = await extractBounded(b, 'application/pdf'); assert.equal(x.fields.quantity, 12500); assert.equal(x.ocrAvailable, false); });
test('metrics expose bounded status labels, not personal IDs or paths', () => { const m = new Metrics(); m.observe(201, 0.05); const s = m.render(); assert(s.includes('status="201"')); assert(s.includes('duration_seconds_bucket')); assert(!s.includes('tenant')); });

import { EventEmitter } from 'node:events';
import { guardClient } from '../src/db.mjs';
test('a checked-out client cannot take the process down on a server-side disconnect', () => {
    const client = new EventEmitter();
    assert.equal(guardClient(client), client);
    assert.equal(client.listenerCount('error'), 1);
    assert.doesNotThrow(() => client.emit('error', Object.assign(Error('Connection terminated unexpectedly'), { code: 'ECONNRESET' })));
});
test('guardClient is applied at every checked-out transaction boundary', async () => {
    for (const file of ['../src/db.mjs', '../src/university/store.mjs', '../src/operations/exports.mjs']) {
        const text = await readFile(new URL(file, import.meta.url), 'utf8');
        assert(text.includes('guardClient(await pool.connect())'), file + ' must guard its checked-out client');
    }
});
