/** Loopback-only test harness: REAL HTTP/router/domain/parser + IN-MEMORY DB and synthetic scanner/storage. */
import{createApp}from'../../src/http.mjs';import{role,fail,id,hash}from'../../src/core.mjs';import{fields}from'../../src/university/core.mjs';import{matchRoute}from'../../src/university/router.mjs';import{readyFixture}from'../carbon/memory.mjs';import{validateUpload}from'../../src/storage.mjs';import{extractImport}from'../../src/ingestion/parser.mjs';import{fileURLToPath}from'node:url';
export async function httpFixture(){
 const f=await readyFixture('ENERGY');await f.s.update('u_c_sources',f.source.id,{code:'MAIN_GRID',name:'Main campus / grid import'});f.source=await f.s.get('u_c_sources',f.source.id);
 const bytes=new Map(),pending=new Set(),cache=new Map();
 const svc={login:async b=>{if(b.tenantId!==f.tenant||b.password!=='FixtureOnly@123')fail(401,'FIXTURE_LOGIN','Use synthetic fixture credentials');const u=f.actors[b.email.split('@')[0].toUpperCase()];if(!u)fail(401,'FIXTURE_LOGIN','Invalid fixture actor');return{token:'TEST-'+b.email.split('@')[0].toUpperCase(),user:u};},authenticate:async header=>{const u=f.actors[String(header).replace('Bearer TEST-','')];if(!u)fail(401,'UNAUTHENTICATED','Fixture sign-in required');return{...u};},publicUser:u=>u,limit:async()=>{},uploadLimit:async()=>{},logout:async()=>({}),readiness:async()=>({ready:true,fixtureOnly:true}),metadata:async()=>({tenant:f.state.tables.tenants[0],periods:f.state.tables.periods,campuses:f.state.tables.campuses}),
  university:async r=>{const m=matchRoute(r.method,r.path);role(r.user,m.route.roles);fields(r.query,m.route.query);const digest=hash(JSON.stringify([r.method,r.path,r.query,r.body]));let ck;if(m.route.cache){if(!r.key||r.key.length<8)fail(422,'IDEMPOTENCY_KEY_REQUIRED','Retain an idempotency key for retries.');ck=r.user.id+':'+r.key;if(cache.has(ck)){if(cache.get(ck).digest!==digest)fail(409,'IDEMPOTENCY_CONFLICT','Key already used.');return structuredClone(cache.get(ck).output);}}const data=await f.s.for(r.user).transaction(s=>m.route.fn(s,r.body,m.params,r.query));const output=m.route.file?{file:data}:{data,status:m.route.status||200};if(ck)cache.set(ck,{digest,output:structuredClone(output)});return output;},
  upload:async(u,name,mime,body)=>{role(u,['ADMIN','ENTRY']);const meta=validateUpload(name,mime,body);const duplicate=f.state.tables.documents.find(d=>d.tenant_id===u.tenant_id&&d.sha256===meta.sha256);if(duplicate)fail(409,'DUPLICATE_FILE','Original already present.',{documentId:duplicate.id,status:duplicate.status});const d=await f.s.for(u).insert('documents',{original_name:meta.name,mime_type:meta.mime,file_size:String(meta.size),sha256:meta.sha256,object_version:'SYNTHETIC_PRIVATE_STORAGE',uploaded_by:u.id,status:'QUEUED',scan_result:null});bytes.set(d.id,Buffer.from(body));const work=(async()=>{const extraction=await extractImport(body,meta.mime);await f.s.for(u).update('documents',d.id,{status:'REVIEW_REQUIRED',scan_result:'CLEAN',scan_engine:'SYNTHETIC_TEST_DOUBLE_NOT_CLAMAV',extraction});})();pending.add(work);work.finally(()=>pending.delete(work));return d;},
  getDocument:async(u,rid)=>f.s.for(u).get('documents',rid),download:async(u,rid)=>{const d=await f.s.for(u).get('documents',rid);await f.s.for(u).evidence([rid],true);return{name:d.original_name,mime:d.mime_type,bytes:bytes.get(rid)};},listResource:async(u,k)=>({items:k==='documents'?f.state.tables.documents:[],nextCursor:null})};
 const cfg={production:false,origins:[],maxInflight:64,maxUploads:2,maxUploadBytes:10485760,metricsToken:'SYNTHETIC',trustProxy:false};const app=createApp(cfg,svc,{log:()=>{}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+app.server.address().port;cfg.origins.push(url);
 return{...f,url,app,async close(){await Promise.all([...pending]);await new Promise(r=>app.server.close(r));},async wait(){await Promise.all([...pending]);}};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){if(process.env.INGESTION_UI_FIXTURE!=='1'||process.env.NODE_ENV==='production')throw Error('Set INGESTION_UI_FIXTURE=1 for this synthetic localhost-only test. Forbidden in production.');const f=await httpFixture();console.log(JSON.stringify({url:f.url,tenantId:f.tenant,periodId:f.period,sourceId:f.source.id,factorId:f.factor.id,fallbackId:f.fallback.id,mode:'SYNTHETIC_FIXTURE_NO_POSTGRES_NO_S3_NO_CLAMAV'}));for(const signal of['SIGINT','SIGTERM'])process.on(signal,()=>f.close().then(()=>process.exit(0)));}
