import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{id}from'../../src/core.mjs';import{ROUTES}from'../../src/university/router.mjs';import{migrationPlan}from'../../scripts/migrate.mjs';import{INGESTION_TABLES}from'../../src/ingestion/schema.mjs';import{httpFixture}from'./http-fixture.mjs';
const p='/api/v2/university/ingestion';async function withHttp(fn){const f=await httpFixture();try{await fn(f);}finally{await f.close();}}
const req=async(f,path,{role='ENTRY',body,key=id(),method=body?'POST':'GET',headers={}}={})=>{const r=await fetch(f.url+path,{method,headers:{Authorization:'Bearer TEST-'+role,...(body?{'Content-Type':'application/json','Idempotency-Key':key}:{}),...headers},body:body?JSON.stringify(body):undefined});return{r,body:r.headers.get('content-type')?.includes('application/json')?await r.json():await r.text()};};
test('17 unique ingestion operations inherit role and retry metadata',()=>{const a=ROUTES.filter(r=>r.path.includes('/ingestion/'));assert.equal(a.length,17);for(const r of a.filter(r=>r.write)){assert.ok(r.cache);assert.ok(!r.roles.includes('LEADERSHIP'));assert.ok(!r.roles.includes('REVIEWER'));}});
test('migration 4 adds four forced RLS tables and immutable receipts',async()=>{assert.deepEqual((await migrationPlan()).map(m=>m.version),[1,2,3,4,5,6]);const s=await readFile('migrations/004_ingestion.sql','utf8');for(const t of Object.keys(INGESTION_TABLES))assert.match(s,new RegExp('CREATE TABLE cs.'+t));assert.match(s,/FORCE ROW LEVEL SECURITY/);assert.match(s,/Imported staging receipts are immutable/);assert.match(s,/UNIQUE INDEX u_i_import_receipt/);assert.match(s,/FOREIGN KEY\(tenant_id,batch_id,file_id\)/);});
test('new UI is real static HTTP with CSP and no external scripts',()=>withHttp(async f=>{let r=await fetch(f.url+'/university/imports');assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/script-src 'self'/);assert.match(await r.text(),/Messy files/);for(const path of ['/ingestion/app.js','/ingestion/style.css'])assert.equal((await fetch(f.url+path)).status,200);}));
test('imports require login and do not accept tenant query switching',()=>withHttp(async f=>{assert.equal((await fetch(f.url+p+'/batches')).status,401);const r=await req(f,p+'/batches?tenantId='+f.tenant);assert.equal(r.r.status,422);}));
test('leadership cannot create import batch',()=>withHttp(async f=>{const r=await req(f,p+'/batches',{role:'LEADERSHIP',body:{name:'Blocked import',kind:'SPREADSHEET',target:'CARBON',periodId:f.period}});assert.equal(r.r.status,403);}));
test('request replay returns same created batch; changed payload conflicts',()=>withHttp(async f=>{const key=id(),body={name:'Retry-safe batch',kind:'SPREADSHEET',target:'CARBON',periodId:f.period};const a=await req(f,p+'/batches',{body,key}),b=await req(f,p+'/batches',{body,key});assert.equal(a.body.data.id,b.body.data.id);assert.equal((await req(f,p+'/batches',{body:{...body,name:'Different'},key})).r.status,409);}));
test('HTTP accepts real XLSX bytes; attaches, normalizes and preserves original download',()=>withHttp(async f=>{const name='University-Messy-Data.xlsx',bytes=await readFile('samples/ingestion/'+name);const upload=await fetch(f.url+'/api/v2/documents/upload',{method:'POST',headers:{Authorization:'Bearer TEST-ENTRY','Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','X-Filename':name,'Idempotency-Key':id()},body:bytes});assert.equal(upload.status,202);const doc=(await upload.json()).data;const b=(await req(f,p+'/batches',{body:{name:'Actual XLSX over HTTP',kind:'SPREADSHEET',target:'CARBON',periodId:f.period}})).body.data;const a=(await req(f,p+'/batches/'+b.id+'/files',{body:{version:b.version,documentIds:[doc.id]}})).body.data;await f.wait();const detail=(await req(f,p+'/files/'+a.files[0].id)).body.data;assert.equal(detail.suggestions[0].headerRow,5);const suggestion=detail.suggestions[0];const r=await req(f,p+'/files/'+a.files[0].id+'/preview',{body:{version:1,plans:[{sheet:suggestion.sheet,headerRow:suggestion.headerRow,mapping:suggestion.mapping,dateOrder:'DMY',defaults:{sourceId:f.source.id,factorId:f.factor.id,fallbackFactorId:f.fallback.id,fallbackReason:'Synthetic approved fallback test.'}}]}});assert.equal(r.r.status,200);assert.equal(r.body.data.summary.review,3);assert.equal(r.body.data.summary.skipped,2);const original=await fetch(f.url+'/api/v2/documents/'+doc.id+'/download',{headers:{Authorization:'Bearer TEST-ENTRY'}});assert.deepEqual(Buffer.from(await original.arrayBuffer()),bytes);assert.equal(await f.s.count('u_c_records'),0);}));
