import test from 'node:test';import assert from 'node:assert/strict';
import {normalizeNumber,normalizeDate,normalizeUnit,normalizeValues,suggestSheet,workbookRows,invoiceRows,suggestGroups,normalizedKey,validatePlan,safeCsvCell,monthRange}from'../../src/ingestion/normalize.mjs';
import{workbook,standard}from'./helpers.mjs';
const base={sheet:'Data',headerRow:1,mapping:{quantity:'A',unit:'B',intervalStart:'C',intervalEnd:'D'}};
for(const[input,expected]of[['1,25,000','125000.000000'],['12,500.50','12500.500000'],['0005','5.000000'],['0','0.000000'],['1.000001','1.000001']])test('number exact '+input,()=>assert.equal(normalizeNumber(input),expected));
for(const input of ['',null,'1,23','1,000,00','1e3','-1','+1','1 000','INR 100','10%','=2+2','1.0000001'])test('number rejects '+input,()=>assert.throws(()=>normalizeNumber(input)));
test('decimal comma is explicit',()=>{assert.equal(normalizeNumber('1.250,50','DECIMAL_COMMA'),'1250.500000');assert.throws(()=>normalizeNumber('1.250,50'));});
for(const input of ['2026-02-29','32/01/2026','45000','04/05/2026','2026-13-01'])test('date does not guess '+input,()=>assert.throws(()=>normalizeDate(input)));
test('declared date order resolves ambiguity',()=>{assert.equal(normalizeDate('04/05/2026','DMY'),'2026-05-04');assert.equal(normalizeDate('04/05/2026','MDY'),'2026-04-05');assert.equal(normalizeDate('29/02/2024'),'2024-02-29');});
for(const[input,unit,mult]of[['MWh','kWh','1000'],['litres','litre','1'],['kl','litre','1000'],['tonnes','kg','1000'],['m\u00b3','m3','1'],['%','percent','1']])test('unit '+input,()=>{const u=normalizeUnit(input);assert.equal(u.unit,unit);assert.equal(u.multiplier,mult);});
test('unit cannot be missing or guessed',()=>{assert.throws(()=>normalizeUnit(''));assert.throws(()=>normalizeUnit('electricity'));});
test('explicit suffix splits exact quantity and normalizes unit',()=>{const r=normalizeValues({quantity:'1.25 MWh',activityDate:'2026-05-31'});assert.equal(r.normalized.quantity,'1250.000000');assert.equal(r.normalized.unit,'kWh');assert.equal(r.issues.filter(i=>i.severity==='ERROR').length,0);});
test('suffix disagreement flags conflict',()=>assert.ok(normalizeValues({quantity:'1.25 MWh',unit:'kWh',activityDate:'2026-05-31'}).issues.some(i=>i.code==='UNIT_CONFLICT')));
test('currency is not consumption',()=>{const r=normalizeValues({amountInr:'INR 12,500.00',unit:'kWh',activityDate:'2026-05-31'});assert.equal(r.normalized.amountInr,'12500.00');assert.ok(r.issues.some(i=>i.code==='MISSING_QUANTITY'));});
test('inverted date interval rejected',()=>assert.ok(normalizeValues({quantity:'2',unit:'kWh',intervalStart:'2026-05-02',intervalEnd:'2026-05-01'}).issues.some(i=>i.code==='DATE_RANGE')));
test('header detection tolerates titles and empty rows',()=>{const e=workbook([['University data'],[],...standard]);assert.equal(suggestSheet(e.sheets[0]).headerRow,3);});
test('ambiguous header alias not silently chosen',()=>{const e=workbook([['Quantity','Consumption','Unit']]);const s=suggestSheet(e.sheets[0]);assert.equal(s.mapping.quantity,undefined);assert.ok(s.warnings.length);});
test('repeated header and total stay visible but skipped',()=>{const r=workbookRows(workbook([...standard,standard[0],['Grand total','',2750]]),base);assert.equal(r.length,4);assert.equal(r[2].skipReason,'REPEATED_HEADER');assert.equal(r[3].skipReason,'SUMMARY_ROW');});
test('wide month columns unpivot exact periods',()=>{const e=workbook([['Unit','Apr 2026','May 2026'],['litre','20','30']]);const s=suggestSheet(e.sheets[0]);const rows=workbookRows(e,{sheet:'Data',headerRow:1,mapping:{unit:'A'},monthColumns:s.monthColumns.map(({column,intervalStart,intervalEnd})=>({column,intervalStart,intervalEnd}))});assert.equal(rows.length,2);assert.equal(rows[1].normalized.intervalEnd,'2026-05-31');assert.equal(rows[1].normalized.quantity,'30.000000');});
test('unlabelled year is not guessed for monthly layout',()=>assert.equal(monthRange('April'),null));
test('hidden row needs explicit inclusion',()=>{const e=workbook(standard,{hiddenRows:[3]});const r=workbookRows(e,base);assert.equal(r[1].skipReason,'HIDDEN_ROW');assert.equal(workbookRows(e,{...base,includeHidden:true})[1].skipReason,null);});
test('formula measurement is never evaluated',()=>{const e=workbook(standard,{formulaCells:['A2']});assert.ok(workbookRows(e,base)[0].issues.some(i=>i.code==='FORMULA_NOT_EVALUATED'));});
test('merged quantity cannot be forward-filled',()=>{const e=workbook(standard,{mergedCells:{A3:'A2'}});assert.ok(workbookRows(e,base)[1].issues.some(i=>i.code==='MERGED_VALUE'));});
test('never forward-fill date or quantity',()=>assert.throws(()=>validatePlan({...base,forwardFill:['quantity']})));
test('mapping cannot reuse a column for quantity and amount',()=>assert.throws(()=>validatePlan({...base,mapping:{quantity:'A',amountInr:'A'}})));
test('unknown mapping fields fail closed',()=>assert.throws(()=>validatePlan({...base,mapping:{tenantId:'A'}})));
test('wide and long-form values cannot compete',()=>assert.throws(()=>validatePlan({...base,monthColumns:[{column:'E',intervalStart:'2026-04-01',intervalEnd:'2026-04-30'}]})));
const page=(n,id='DEMO-001',extra='')=>({page:n,text:`Vendor: Synthetic Energy\nInvoice No: ${id}\nConsumption: 1.234567 MWh\nAmount Payable: INR 11111.00\nPeriod Start: 2026-04-01\nPeriod End: 2026-04-30\n${extra}`});
test('invoice decimal normalization retains six places',()=>assert.equal(invoiceRows({pages:[page(1)],pageCount:1},{})[0].normalized.quantity,'1234.567000'));
test('separate invoice identifiers create page groups',()=>assert.equal(suggestGroups({pages:[page(1),page(2,'DEMO-002')]}).length,2));
test('same invoice continuing to another page grouped together',()=>assert.deepEqual(suggestGroups({pages:[page(1),{page:2,text:'Continued charges'}]}),[{pageStart:1,pageEnd:2,defaults:{}}]));
test('merged distinct invoice identifiers block review',()=>assert.ok(invoiceRows({pages:[page(1),page(2,'DEMO-002')],pageCount:2},{groups:[{pageStart:1,pageEnd:2}]} )[0].issues.some(i=>i.code==='MULTIPLE_INVOICES')));
test('invoice issue date is not a consumption date',()=>{const r=invoiceRows({pages:[{page:1,text:'Vendor: X\nInvoice No: DEMO-1\nInvoice Date: 2026-05-01\nConsumption: 1 kWh'}]},{});assert.ok(r[0].issues.some(i=>i.code==='MISSING_DATE'));});
test('multiple quantity lines never auto-summed',()=>{const r=invoiceRows({pages:[page(1,'DEMO-001','Consumption: 90 kWh')]},{});assert.ok(r[0].issues.some(i=>i.code==='MISSING_QUANTITY'));});
test('no OCR output is fabricated',()=>{const r=invoiceRows({pages:[{page:1,text:''}],pageCount:1},{});assert.ok(r[0].issues.some(i=>i.code==='MANUAL_EXTRACTION'));assert.ok(r[0].issues.some(i=>i.code==='MISSING_QUANTITY'));});
test('page ranges cannot exceed file',()=>assert.throws(()=>invoiceRows({pages:[page(1)],pageCount:1},{groups:[{pageStart:1,pageEnd:2}]})));
test('invoice dedupe survives capitalization and punctuation',()=>assert.equal(normalizedKey('CARBON',{vendor:'My energy',invoiceNumber:'INV-001'}),normalizedKey('EMISSION',{vendor:'MY ENERGY',invoiceNumber:'INV001'})));
test('different explicit line IDs remain distinguishable',()=>assert.notEqual(normalizedKey('CARBON',{vendor:'X',invoiceNumber:'1',lineRef:'A'}),normalizedKey('CARBON',{vendor:'X',invoiceNumber:'1',lineRef:'B'})));
test('CSV formula injection neutralized without dropping text',()=>{assert.equal(safeCsvCell('=1+1'),'"\'=1+1"');assert.equal(safeCsvCell('a"b'),'"a""b"');});
