import { role, WRITERS, REVIEWERS, version } from '../core.mjs';
import { fields,text,uuid,day,decimal,choice,bool,code,reason,evidenceIds,dateRange,overlaps,scaled,KPI_TEMPLATES,fail } from './core.mjs';
export function taskAccess(user,task,{write=false,review=false}={}){
  if(write){role(user,WRITERS);if(user.role!=='ADMIN'&&task.assignee_id!==user.id)fail(404,'NOT_FOUND','Task not found.');}
  else if(review){role(user,REVIEWERS);if(user.role!=='ADMIN'&&task.reviewer_id!==user.id)fail(403,'NOT_ASSIGNED_REVIEWER','This task is assigned to another reviewer.');}
  else if(user.role==='ENTRY'&&task.assignee_id!==user.id)fail(404,'NOT_FOUND','Task not found.');
}
export function authorOnly(user,record){if(record.created_by!==user.id)fail(403,'AUTHOR_REQUIRED','Only the original author may change these draft values. An administrator may reject the submission but cannot edit another author\'s evidence and then approve it.');}
export function independent(user,record){role(user,REVIEWERS);if(record.created_by===user.id)fail(403,'SELF_APPROVAL','Another person must approve this record.');}
export async function createDepartment(s,b){fields(b,['campusId','name','code','ownerId']);await s.location(uuid(b.campusId));await s.userRef(uuid(b.ownerId),['ADMIN','ENTRY','REVIEWER']);const r=await s.insert('u_departments',{campus_id:b.campusId,name:text(b.name,'name',160),code:code(b.code),owner_id:b.ownerId});await s.audit('U_DEPARTMENT_CREATED',r.id);return r;}
export function kpiInput(b){fields(b,['code','name','domain','unit','aggregation','evidenceRequired','maxValue','guidance']);const domain=choice(b.domain,['ENERGY','WATER','WASTE','TRANSPORT','SOCIAL','GOVERNANCE','ACADEMIC','NORMALIZATION'],'domain');const unit=choice(b.unit,['kWh','m3','kg','litre','passenger_km','vehicle_km','FTE','m2','hour','count','percent','INR'],'unit');const agg=choice(b.aggregation,['SUM','LATEST'],'aggregation');
  if(['FTE','m2','percent'].includes(unit)&&agg!=='LATEST')fail(422,'AGGREGATION','FTE, floor area and percentages are point-in-time values, not additive time-series metrics.');
  if(domain==='NORMALIZATION'&&(!['STUDENT_FTE','STAFF_FTE','FLOOR_AREA_M2'].includes(b.code)||unit!==({STUDENT_FTE:'FTE',STAFF_FTE:'FTE',FLOOR_AREA_M2:'m2'}[b.code])||agg!=='LATEST'))fail(422,'NORMALIZATION','Use the supplied campus-wide normalization definitions.');
  return {code:code(b.code),name:text(b.name,'name',180),domain,unit,aggregation:agg,evidence_required:bool(b.evidenceRequired,'evidenceRequired'),max_value:b.maxValue==null?null:decimal(b.maxValue,'maxValue',6,true),guidance:reason(b.guidance)};}
export async function createKpi(s,b){const r=await s.insert('u_kpis',{...kpiInput(b),created_by:s.user.id});await s.audit('U_KPI_CREATED',r.id);return r;}
export async function installCatalog(s,b){fields(b,[]);const existing=await s.rows('u_kpis',{},1000),codes=new Set(existing.map(x=>x.code));const added=[];for(const k of KPI_TEMPLATES)if(!codes.has(k.code))added.push(await createKpi(s,k));return {added:added.length,items:added,alreadyPresent:KPI_TEMPLATES.length-added.length,note:'No measurements or emission factors are fabricated or seeded.'};}
export async function createTask(s,b){fields(b,['periodId','campusId','departmentId','kpiId','assigneeId','reviewerId','bucket','intervalStart','intervalEnd','dueDate']);const p=await s.period(uuid(b.periodId));await s.location(uuid(b.campusId),b.departmentId?uuid(b.departmentId):null);const k=await s.get('u_kpis',uuid(b.kpiId));await s.userRef(uuid(b.assigneeId),WRITERS);await s.userRef(uuid(b.reviewerId),REVIEWERS);
  if(b.assigneeId===b.reviewerId)fail(422,'SEPARATE_REVIEWER','Choose a different assignee and reviewer.');const [start,end]=dateRange(b.intervalStart,b.intervalEnd);
  if(start<p.start_date||end>p.end_date)fail(422,'DATE_OUTSIDE_PERIOD','Collection interval must be inside the reporting period.');
  let bucket=code(b.bucket);const due=day(b.dueDate);if(due<end)fail(422,'DUE_DATE','The due date cannot precede the end of the measurement interval.');
  if(k.domain==='NORMALIZATION'&&(b.departmentId||bucket!=='CAMPUS_TOTAL'||start!==p.start_date||end!==p.end_date))fail(422,'NORMALIZATION_BOUNDARY','Normalization uses one CAMPUS_TOTAL bucket for the whole annual period, without a department.');
  await s.lockKey(['task',p.id,b.campusId,k.id,bucket].join(':'));
  const prior=await s.rows('u_tasks',{period_id:p.id,campus_id:b.campusId,kpi_id:k.id,bucket});
  if(prior.some(t=>overlaps(t,{interval_start:start,interval_end:end})))fail(409,'OVERLAPPING_TASK','This KPI source already has an overlapping interval. Do not double count the same meter or source.');
  const r=await s.insert('u_tasks',{period_id:p.id,campus_id:b.campusId,department_id:b.departmentId||null,kpi_id:k.id,assignee_id:b.assigneeId,reviewer_id:b.reviewerId,bucket,interval_start:start,interval_end:end,due_date:due,created_by:s.user.id});await s.audit('U_TASK_CREATED',r.id,{assigneeId:r.assignee_id,reviewerId:r.reviewer_id});return r;}
export async function getTask(s,taskId){const t=await s.get('u_tasks',uuid(taskId));taskAccess(s.user,t);return {...t,kpi:await s.get('u_kpis',t.kpi_id),submissions:await s.rows('u_submissions',{task_id:t.id},100)};}
async function lockTask(s,taskId){const seen=await s.get('u_tasks',uuid(taskId));await s.period(seen.period_id);return s.get('u_tasks',seen.id,{lock:true});}
function submissionValues(k,b){choice(b.unit,[k.unit],'unit');const v=decimal(b.value,'value',6,true);if(k.max_value!==null&&k.max_value!==undefined&&scaled(v)>scaled(k.max_value))fail(422,'RANGE_CHECK','Value exceeds the KPI maximum.');if(['count'].includes(k.unit)&&scaled(v)%1000000n!==0n)fail(422,'WHOLE_COUNT','Count KPIs require a whole number.');if(k.unit==='percent'&&scaled(v)>100000000n)fail(422,'RANGE_CHECK','Percentages must not exceed 100.');return {value:v,unit:k.unit,notes:text(b.notes,'notes',2000,true)||'',evidence_ids:evidenceIds(b.evidenceIds)};}
export async function createSubmission(s,taskId,b){fields(b,['taskVersion','value','unit','notes','evidenceIds','correctionReason']);const t=await lockTask(s,taskId);taskAccess(s.user,t,{write:true});version(t,b.taskVersion);if(t.status==='WAIVED')fail(409,'TASK_WAIVED','This task has been waived.');const k=await s.get('u_kpis',t.kpi_id),prior=await s.rows('u_submissions',{task_id:t.id},100);
  if(prior.some(r=>['DRAFT','SUBMITTED'].includes(r.status)))fail(409,'PENDING_REVISION','Finish or reject the existing draft before starting another revision.');const values=submissionValues(k,b);await s.evidence(values.evidence_ids,false);
  const r=await s.insert('u_submissions',{task_id:t.id,revision:Math.max(0,...prior.map(r=>r.revision))+1,...values,created_by:s.user.id,correction_reason:prior.some(r=>r.status==='APPROVED')?reason(b.correctionReason):null});
  await s.update('u_tasks',t.id,{status:'OPEN'});await s.audit('U_SUBMISSION_DRAFTED',r.id,{taskId:t.id,revision:r.revision});return r;}
export async function editSubmission(s,rid,b){fields(b,['version','value','unit','notes','evidenceIds']);const seen=await s.get('u_submissions',uuid(rid)),t=await lockTask(s,seen.task_id);taskAccess(s.user,t,{write:true});const old=await s.get('u_submissions',seen.id,{lock:true});version(old,b.version);authorOnly(s.user,old);
  if(!['DRAFT','REJECTED'].includes(old.status))fail(409,'INVALID_STATE','Only a draft or rejected submission can be edited.');const prior=await s.rows('u_submissions',{task_id:t.id},100);if(prior.some(r=>r.revision>old.revision))fail(409,'OLDER_REVISION','Create or edit the latest revision instead.');const k=await s.get('u_kpis',t.kpi_id),values=submissionValues(k,b);await s.evidence(values.evidence_ids,false);
  const r=await s.update('u_submissions',old.id,{...values,status:'DRAFT',rejection_reason:null});await s.update('u_tasks',t.id,{status:'OPEN'});await s.audit('U_SUBMISSION_EDITED',r.id,{revision:r.revision});return r;}
export async function submissionAction(s,rid,action,b){fields(b,['version','reason']);const seen=await s.get('u_submissions',uuid(rid)),t=await lockTask(s,seen.task_id),old=await s.get('u_submissions',seen.id,{lock:true});version(old,b.version);const k=await s.get('u_kpis',t.kpi_id);
  if(action==='submit'){taskAccess(s.user,t,{write:true});authorOnly(s.user,old);if(old.status!=='DRAFT')fail(409,'INVALID_STATE','Only a draft can be submitted.');await s.evidence(old.evidence_ids,k.evidence_required);const r=await s.update('u_submissions',old.id,{status:'SUBMITTED'});await s.audit('U_SUBMISSION_SUBMITTED',r.id);return r;}
  taskAccess(s.user,t,{review:true});independent(s.user,old);if(old.status!=='SUBMITTED')fail(409,'INVALID_STATE','Only submitted values can be reviewed.');
  if(action==='reject'){const r=await s.update('u_submissions',old.id,{status:'REJECTED',rejection_reason:reason(b.reason)});await s.audit('U_SUBMISSION_REJECTED',r.id,{reason:r.rejection_reason});return r;}
  if(action!=='approve')fail(404,'NOT_FOUND','Unknown transition.');const evidence=await s.evidence(old.evidence_ids,k.evidence_required);
  const snap=await s.insert('u_metric_snapshots',{submission_id:old.id,task_id:t.id,revision:old.revision,period_id:t.period_id,campus_id:t.campus_id,kpi_id:k.id,bucket:t.bucket,interval_start:t.interval_start,interval_end:t.interval_end,value:old.value,unit:k.unit,aggregation:k.aggregation,kpi_code:k.code,evidence,approved_by:s.user.id});
  const r=await s.update('u_submissions',old.id,{status:'APPROVED',approved_by:s.user.id});await s.update('u_tasks',t.id,{status:'COMPLETE'});await s.audit('U_METRIC_APPROVED',r.id,{snapshotId:snap.id,revision:old.revision});return {...r,snapshotId:snap.id};}
export async function waiveTask(s,rid,b){fields(b,['version','reason']);const t=await lockTask(s,rid);version(t,b.version);if(t.status!=='OPEN')fail(409,'INVALID_STATE','Only open tasks can be waived.');const subs=await s.rows('u_submissions',{task_id:t.id},100);if(subs.some(r=>r.status!=='REJECTED'))fail(409,'EXISTING_SUBMISSIONS','Resolve submitted, draft or approved values before waiving a task.');const r=await s.update('u_tasks',t.id,{status:'WAIVED',waiver_reason:reason(b.reason)});await s.audit('U_TASK_WAIVED',r.id,{reason:r.waiver_reason});return r;}
