import { randomBytes, timingSafeEqual } from 'node:crypto';
import { version, id } from '../core.mjs';
import { fields,text,code,uuid,day,integer,choice,reason,evidenceIds,questionnaire,validateAnswers,materialityTopics,validateScores,materialitySummary,STAKEHOLDERS,decimal,scaled,hash,fail } from './core.mjs';
import { independent } from './collection.mjs';
export async function createSupplier(s,b){fields(b,['name','code','contactEmail','category']);const email=text(b.contactEmail,'contactEmail',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(422,'INVALID_EMAIL','Supply a valid contact email.');const r=await s.insert('u_suppliers',{name:text(b.name,'name',180),code:code(b.code),contact_email:email,category:text(b.category,'category',100),created_by:s.user.id});await s.audit('U_SUPPLIER_CREATED',r.id);return r;}
export async function createSupplierRequest(s,b){fields(b,['supplierId','periodId','title','questions','dueDate']);await s.period(uuid(b.periodId));await s.get('u_suppliers',uuid(b.supplierId));const r=await s.insert('u_supplier_requests',{supplier_id:b.supplierId,period_id:b.periodId,title:text(b.title,'title',200),questions:questionnaire(b.questions),due_date:day(b.dueDate),created_by:s.user.id});await s.audit('U_SUPPLIER_REQUEST_CREATED',r.id);return r;}
export function requestAccess(user,r){if(user.role==='ENTRY'&&r.created_by!==user.id)fail(404,'NOT_FOUND','Record not found.');}
async function parent(s,table,rid,{write=true,lock=true}={}){const seen=await s.get(table,uuid(rid));await s.period(seen.period_id,write);return s.get(table,rid,{lock});}
export async function supplierEvidence(s,rid,b){fields(b,['version','evidenceIds']);const r=await parent(s,'u_supplier_requests',rid);requestAccess(s.user,r);version(r,b.version);if(r.status!=='SUBMITTED')fail(409,'INVALID_STATE','Attach evidence after the supplier has submitted their answers.');const ids=evidenceIds(b.evidenceIds);await s.evidence(ids,true);const out=await s.update('u_supplier_requests',r.id,{evidence_ids:ids});await s.audit('U_SUPPLIER_EVIDENCE_ATTACHED',r.id,{count:ids.length});return out;}
export async function reviewSupplier(s,rid,action,b){fields(b,['version','reason']);const r=await parent(s,'u_supplier_requests',rid);version(r,b.version);independent(s.user,r);if(r.status!=='SUBMITTED')fail(409,'INVALID_STATE','Only a submitted supplier response can be reviewed.');
  if(action==='approve'){validateAnswers(r.questions,r.answers);await s.evidence(r.evidence_ids,true);const out=await s.update('u_supplier_requests',r.id,{status:'APPROVED',approved_by:s.user.id});await s.audit('U_SUPPLIER_RESPONSE_APPROVED',r.id,{note:'Supplier responses do not automatically post emissions.'});return out;}
  if(action==='reject'){const out=await s.update('u_supplier_requests',r.id,{status:'REJECTED',rejection_reason:reason(b.reason)});await s.audit('U_SUPPLIER_RESPONSE_REJECTED',r.id,{reason:out.rejection_reason});return out;}fail(404,'NOT_FOUND','Unknown action.');}
export async function createMateriality(s,b){fields(b,['periodId','title','topics','impactThreshold','financialThreshold','minResponses']);await s.period(uuid(b.periodId));const i=decimal(b.impactThreshold,'impactThreshold',2),f=decimal(b.financialThreshold,'financialThreshold',2);if(scaled(i)<1000000n||scaled(i)>5000000n||scaled(f)<1000000n||scaled(f)>5000000n)fail(422,'THRESHOLD_RANGE','Exploratory thresholds must be between 1 and 5.');const r=await s.insert('u_materiality',{period_id:b.periodId,title:text(b.title,'title',200),topics:materialityTopics(b.topics),impact_threshold:i,financial_threshold:f,min_responses:integer(b.minResponses,5,100,'minResponses'),created_by:s.user.id});await s.audit('U_MATERIALITY_CREATED',r.id);return r;}
export async function materialityStats(s,rid){const r=await s.get('u_materiality',uuid(rid));requestAccess(s.user,r);const responses=await s.rows('u_responses',{assessment_id:r.id},5000);return {assessmentId:r.id,status:r.status,...(r.status==='APPROVED'?r.snapshot:materialitySummary(r,responses))};}
export async function materialityAction(s,rid,action,b){fields(b,['version','reason']);const r=await parent(s,'u_materiality',rid);version(r,b.version);let updates;
  if(action==='close'){requestAccess(s.user,r);if(r.status!=='OPEN')fail(409,'INVALID_STATE','Assessment is not open.');updates={status:'CLOSED'};}
  else if(action==='reopen'){requestAccess(s.user,r);if(r.status!=='CLOSED')fail(409,'INVALID_STATE','Only a closed, unpublished assessment can be reopened.');updates={status:'OPEN'};reason(b.reason);}
  else if(action==='approve'){independent(s.user,r);if(r.status!=='CLOSED')fail(409,'INVALID_STATE','Close the assessment before approval.');const responses=await s.rows('u_responses',{assessment_id:r.id},5000),snapshot=materialitySummary(r,responses);if(snapshot.suppressed)fail(422,'INSUFFICIENT_RESPONSES','Collect the minimum number of responses before publishing.');updates={status:'APPROVED',approved_by:s.user.id,snapshot};}
  else fail(404,'NOT_FOUND','Unknown action.');const out=await s.update('u_materiality',r.id,updates);await s.audit('U_MATERIALITY_'+out.status,r.id,{reason:b.reason||null});return out;}
export function capabilityToken(tenant,inviteId){return `${uuid(tenant)}.${uuid(inviteId)}.${randomBytes(32).toString('base64url')}`;}
export function parseCapability(header){const m=/^Capability ([0-9a-f-]{36})\.([0-9a-f-]{36})\.([A-Za-z0-9_-]{43})$/.exec(header||'');if(!m)fail(401,'INVALID_CAPABILITY','A valid invitation capability is required.');try{return {tenantId:uuid(m[1]),inviteId:uuid(m[2]),token:header.slice(11)};}catch{fail(401,'INVALID_CAPABILITY','A valid invitation capability is required.');}}
export function validateCapability(invite,token,now=Date.now()){const digest=hash(token),stored=String(invite?.token_hash||'');if(!invite||! /^[a-f0-9]{64}$/.test(stored)||!timingSafeEqual(Buffer.from(digest),Buffer.from(stored))||invite.revoked||new Date(invite.expires_at).getTime()<=now)fail(401,'INVALID_CAPABILITY','Invitation has expired or was revoked.');}
export async function issueInvite(s,kind,rid,b){fields(b,['version','expiresInDays','stakeholderGroup']);const days=integer(b.expiresInDays,1,30,'expiresInDays');const table=kind==='SUPPLIER'?'u_supplier_requests':'u_materiality',r=await parent(s,table,rid);requestAccess(s.user,r);version(r,b.version);let group=null;
  if(kind==='SUPPLIER'){if(!['DRAFT','OPEN','REJECTED'].includes(r.status))fail(409,'INVALID_STATE','Reopen only draft/open/rejected supplier requests.');if(b.stakeholderGroup!=null)fail(422,'UNEXPECTED_GROUP','Supplier requests do not have stakeholder groups.');for(const old of await s.rows('u_invites',{kind,target_id:r.id},1000))if(!old.revoked)await s.update('u_invites',old.id,{revoked:true});await s.update(table,r.id,{status:'OPEN',answers:null,rejection_reason:null,evidence_ids:[]});}
  else {if(r.status!=='OPEN')fail(409,'INVALID_STATE','Assessment is not open.');group=choice(b.stakeholderGroup,STAKEHOLDERS,'stakeholderGroup');if(await s.count('u_invites',{kind,target_id:r.id})>=5000)fail(422,'INVITATION_LIMIT','This assessment is capped at 5000 invitations.');}
  const iid=id(),token=capabilityToken(s.tenant,iid),expires=new Date(Date.now()+days*86400000).toISOString();await s.insert('u_invites',{id:iid,kind,target_id:r.id,token_hash:hash(token),stakeholder_group:group,expires_at:expires,created_by:s.user.id});await s.audit('U_INVITATION_ISSUED',iid,{kind,targetId:r.id,expiresAt:expires});
  return {id:iid,token,expiresAt:expires,portalPath:'/university/portal',delivery:'Copy and share privately through your approved channel. No email was sent. Token is returned only in this response and is not stored in plaintext.',requestVersion:kind==='SUPPLIER'?r.version+1:r.version};}
export async function revokeInvite(s,rid,b){fields(b,['reason']);const inv=await s.get('u_invites',uuid(rid));requestAccess(s.user,inv);await s.update('u_invites',inv.id,{revoked:true});await s.audit('U_INVITATION_REVOKED',inv.id,{reason:reason(b.reason)});return {id:inv.id,revoked:true};}
/** Invoked only after token-specific and IP-based rate limiting in router.mjs. */
export async function portal(s,parsed,body=null){const raw=await s.maybe('u_invites',parsed.inviteId);validateCapability(raw,parsed.token);
  const tenant=await s.get('tenants',s.tenant);if(tenant.status!=='ACTIVE')fail(401,'INVALID_CAPABILITY','Invitation is not active.');
  const table=raw.kind==='SUPPLIER'?'u_supplier_requests':'u_materiality',seen=await s.get(table,raw.target_id);
  await s.period(seen.period_id,body!==null);const target=await s.get(table,raw.target_id,{lock:body!==null});const inv=await s.get('u_invites',raw.id,{lock:body!==null});validateCapability(inv,parsed.token);
  if(body===null){return {kind:inv.kind,id:target.id,title:target.title,status:target.status,version:target.version,consumed:inv.consumed,expiresAt:inv.expires_at,
    ...(inv.kind==='SUPPLIER'?{questions:target.questions,answers:target.answers}:{topics:target.topics,scale:{minimum:1,maximum:5},privacy:'Do not include names, addresses, student IDs or sensitive personal data. Only aggregate results are published.'})};}
  if(inv.consumed)fail(409,'CAPABILITY_USED','This single-use invitation has already been submitted.');if(target.status!=='OPEN')fail(409,'PORTAL_CLOSED','This request is not open for responses.');
  if(inv.kind==='SUPPLIER'){fields(body,['version','answers','attestation']);version(target,body.version);if(body.attestation!==true)fail(422,'ATTESTATION_REQUIRED','Confirm that these answers have been reviewed by the supplier.');const answers=validateAnswers(target.questions,body.answers);await s.update(table,target.id,{answers,status:'SUBMITTED'});}
  else{fields(body,['version','scores','consent']);version(target,body.version);if(body.consent!==true)fail(422,'CONSENT_REQUIRED','Explicit participation consent is required.');const scores=validateScores(target.topics,body.scores);await s.insert('u_responses',{assessment_id:target.id,invite_id:inv.id,stakeholder_group:inv.stakeholder_group,scores});}
  await s.update('u_invites',inv.id,{consumed:true});await s.audit('U_PORTAL_RESPONSE_RECEIVED',target.id,{kind:inv.kind,invitationId:inv.id});return {received:true,kind:inv.kind,inventoryPosted:false};}
