import { version } from '../core.mjs';
import { fields,uuid,reason,factorInput,emissionInput,checkFactor,product,csvParse,choice,integer,fail } from './core.mjs';
import { authorOnly, independent } from './collection.mjs';
export async function createFactor(s,b){const r=await s.insert('u_factors',{...factorInput(b),created_by:s.user.id});await s.audit('U_FACTOR_CREATED',r.id,{category:r.category,version:r.version_label});return r;}
export async function approveFactor(s,rid,b){fields(b,['version']);const f=await s.get('u_factors',uuid(rid),{lock:true});version(f,b.version);independent(s.user,f);if(f.status!=='DRAFT')fail(409,'INVALID_STATE','Factor is already approved.');const r=await s.update('u_factors',f.id,{status:'APPROVED',approved_by:s.user.id});await s.audit('U_FACTOR_APPROVED',r.id,{source:r.source,version:r.version_label});return r;}
export function emissionAccess(user,r){if(user.role==='ENTRY'&&r.created_by!==user.id)fail(404,'NOT_FOUND','Record not found.');}
export async function validateEmission(s,a){if(['SCOPE_1','SCOPE_2'].includes(a.scope)&&await s.count('u_c_period_modes',{period_id:a.period_id}))fail(409,'ENHANCED_SCOPE12_ACTIVE','Use the enhanced carbon source ledger for this period.');const p=await s.period(a.period_id);if(a.activity_date<p.start_date||a.activity_date>p.end_date)fail(422,'DATE_OUTSIDE_PERIOD','Activity must fall within the reporting period.');await s.location(a.campus_id,a.department_id);const f=await s.get('u_factors',a.factor_id);checkFactor(a,f);await s.evidence(a.evidence_ids,false);
  if(a.replaces_id){const old=await s.get('u_emissions',a.replaces_id);emissionAccess(s.user,old);if(old.period_id!==a.period_id)fail(422,'CORRECTION_PERIOD','A replacement must belong to the same reporting period.');const approved=await s.count('u_voids',{emission_id:old.id,status:'APPROVED'});if(!approved)fail(409,'VOID_REQUIRED','An approved void must precede a replacement entry.');}return f;}
export async function insertEmission(s,a){const r=await s.insert('u_emissions',{...a,created_by:s.user.id});await s.audit('U_EMISSION_DRAFTED',r.id,{category:r.category,externalKey:r.external_key,replacesId:r.replaces_id});return r;}
export async function createEmission(s,b){const a=emissionInput(b);await validateEmission(s,a);return insertEmission(s,a);}
export async function getEmission(s,rid){const r=await s.get('u_emissions',uuid(rid));emissionAccess(s.user,r);return {...r,calculations:await s.rows('u_calculations',{emission_id:r.id},1),voids:await s.rows('u_voids',{emission_id:r.id},100)};}
export async function editEmission(s,rid,b){const {version:expected,...input}=b,a=emissionInput(input),seen=await s.get('u_emissions',uuid(rid));emissionAccess(s.user,seen);
  if(a.period_id!==seen.period_id||a.replaces_id!==seen.replaces_id)fail(422,'IMMUTABLE_REFERENCE','Keep the original period and replacement reference when editing.');await s.period(seen.period_id);const old=await s.get('u_emissions',seen.id,{lock:true});version(old,expected);authorOnly(s.user,old);
  if(!['DRAFT','REJECTED'].includes(old.status))fail(409,'INVALID_STATE','Only draft or rejected entries can be edited.');await validateEmission(s,a);const r=await s.update('u_emissions',old.id,{...a,status:'DRAFT',rejection_reason:null});await s.audit('U_EMISSION_EDITED',r.id);return r;}
export async function emissionAction(s,rid,action,b){fields(b,['version','reason']);const seen=await s.get('u_emissions',uuid(rid));emissionAccess(s.user,seen);await s.period(seen.period_id);const old=await s.get('u_emissions',seen.id,{lock:true});version(old,b.version);
  if(action==='submit'){authorOnly(s.user,old);if(old.status!=='DRAFT')fail(409,'INVALID_STATE','Only a draft can be submitted.');await s.evidence(old.evidence_ids,true);const r=await s.update('u_emissions',old.id,{status:'SUBMITTED'});await s.audit('U_EMISSION_SUBMITTED',r.id);return r;}
  independent(s.user,old);if(old.status!=='SUBMITTED')fail(409,'INVALID_STATE','Only submitted entries can be reviewed.');if(action==='reject'){const r=await s.update('u_emissions',old.id,{status:'REJECTED',rejection_reason:reason(b.reason)});await s.audit('U_EMISSION_REJECTED',r.id,{reason:r.rejection_reason});return r;}
  if(action!=='approve')fail(404,'NOT_FOUND','Unknown transition.');const f=await s.get('u_factors',old.factor_id);checkFactor(old,f);const evidence=await s.evidence(old.evidence_ids,true);
  if(old.scope==='SCOPE_3'){await s.lockKey('scope3:'+old.period_id+':'+old.scope3_category);const entries=await s.rows('u_scope3_screenings',{period_id:old.period_id,category_number:old.scope3_category},1);if(entries[0]?.decision!=='INCLUDED')fail(422,'SCOPE3_SCREENING','Declare this Scope 3 category INCLUDED with a boundary rationale before approval.');}
  const kg=product(old.quantity,f.value),provenance={formula:'quantity x factor',quantity:old.quantity,unit:old.unit,rounding:'half-up to 6 decimal kg CO2e',factor:{id:f.id,value:f.value,unit:f.unit,method:f.method,version:f.version_label,source:f.source,sourceUrl:f.source_url,region:f.region,boundary:f.boundary,validFrom:f.valid_from,validTo:f.valid_to,currency:f.currency,priceYear:f.price_year},evidence,assumptions:old.assumptions,dataQuality:old.data_quality,approvedBy:s.user.id,review:'INTERNAL_MAKER_CHECKER',scope:old.scope,scope3Category:old.scope3_category};
  const calculation=await s.insert('u_calculations',{emission_id:old.id,factor_id:f.id,quantity:old.quantity,factor_value:f.value,kg_co2e:kg,provenance});
  const r=await s.update('u_emissions',old.id,{status:'CALCULATED',approved_by:s.user.id});await s.audit('U_EMISSION_CALCULATED',r.id,{calculationId:calculation.id,kgCo2e:kg,factorId:f.id});return {...r,calculation};}
export async function requestVoid(s,rid,b){fields(b,['version','reason']);const old=await s.get('u_emissions',uuid(rid));emissionAccess(s.user,old);await s.period(old.period_id);const locked=await s.get('u_emissions',old.id,{lock:true});version(locked,b.version);if(locked.status!=='CALCULATED')fail(409,'INVALID_STATE','Only a calculated entry can be voided.');if((await s.rows('u_voids',{emission_id:old.id},100)).some(v=>['SUBMITTED','APPROVED'].includes(v.status)))fail(409,'EXISTING_VOID','An active void already exists.');const r=await s.insert('u_voids',{emission_id:old.id,reason:reason(b.reason),created_by:s.user.id});await s.audit('U_VOID_REQUESTED',r.id,{emissionId:old.id,reason:r.reason});return r;}
export async function reviewVoid(s,rid,action,b){fields(b,['version','reason']);const seen=await s.get('u_voids',uuid(rid)),a=await s.get('u_emissions',seen.emission_id);await s.period(a.period_id);const old=await s.get('u_voids',seen.id,{lock:true});version(old,b.version);independent(s.user,old);if(old.status!=='SUBMITTED')fail(409,'INVALID_STATE','Void is not pending.');const status=choice(action,['approve','reject'],'void action')==='approve'?'APPROVED':'REJECTED';const r=await s.update('u_voids',old.id,{status,approved_by:status==='APPROVED'?s.user.id:null});await s.audit('U_VOID_'+status,r.id,{emissionId:a.id,reason:status==='REJECTED'?reason(b.reason):old.reason});return r;}
export async function setScreening(s,b){fields(b,['periodId','categoryNumber','decision','rationale','version']);const p=await s.period(uuid(b.periodId));const n=integer(b.categoryNumber,1,15,'categoryNumber'),decision=choice(b.decision,['INCLUDED','EXCLUDED','NOT_ASSESSED'],'decision'),rationale=reason(b.rationale);
  await s.lockKey('scope3:'+p.id+':'+n);
  if(decision!=='INCLUDED'&&await s.count('u_emissions',{period_id:p.id,scope3_category:n,status:'CALCULATED'}))fail(409,'CATEGORY_HAS_CALCULATIONS','A category with calculated records cannot be excluded or reset.');
  const prior=await s.rows('u_scope3_screenings',{period_id:p.id,category_number:n},1);let r;
  if(prior.length){const old=await s.get('u_scope3_screenings',prior[0].id,{lock:true});version(old,b.version);r=await s.update('u_scope3_screenings',old.id,{decision,rationale});await s.audit('U_SCOPE3_SCREENING_UPDATED',r.id,{before:old.decision,decision,rationale});}
  else {r=await s.insert('u_scope3_screenings',{period_id:p.id,category_number:n,decision,rationale,created_by:s.user.id});await s.audit('U_SCOPE3_SCREENING_CREATED',r.id,{decision,rationale});}return r;}
export function csvEmissionRows(csv){return csvParse(csv).map((r,i)=>{const input={...r};for(const key of ['departmentId','replacesId','currency','priceYear'])if(input[key]==='')delete input[key];if(input.priceYear!==undefined){if(!/^\d{4}$/.test(input.priceYear))fail(422,'CSV_PRICE_YEAR',`Row ${i+2}: priceYear must be four digits.`);input.priceYear=Number(input.priceYear);}if(input.evidenceIds!==undefined)input.evidenceIds=input.evidenceIds?input.evidenceIds.split('|'):[];return {line:i+2,input};});}
export async function importEmissions(s,b,{commit=false}={}){fields(b,['csv']);const rows=csvEmissionRows(b.csv),valid=[],errors=[],keys=new Set();
  for(const row of rows){try{const a=emissionInput(row.input);if(keys.has(a.external_key))fail(409,'DUPLICATE_EXTERNAL_KEY','Repeated source key in this CSV.');keys.add(a.external_key);if(await s.count('u_emissions',{external_key:a.external_key}))fail(409,'DUPLICATE_EXTERNAL_KEY','Source key already exists.');await validateEmission(s,a);valid.push(a);}catch(e){if(!e.status)throw e;errors.push({line:row.line,code:e.code,message:e.message});}}
  if(errors.length){if(commit)fail(422,'IMPORT_REJECTED','No rows were imported. Correct every validation error before committing.',{errors});return {dryRun:true,valid:false,totalRows:rows.length,errors,imported:0};}
  if(!commit)return {dryRun:true,valid:true,totalRows:rows.length,errors:[],preview:valid,imported:0,note:'References, units, factors and duplicate source keys checked. Approval is still required after import.'};
  const items=[];for(const a of valid)items.push(await insertEmission(s,a));return {dryRun:false,imported:items.length,items,atomic:true};}
