import { selectedInventoryTotal } from './carbon/reporting.mjs';
import { version } from '../core.mjs';
import { fields,text,uuid,day,decimal,integer,choice,reason,scaled,format,sum,ratio,percentOf,pcfInput,calculatePcf,fail } from './core.mjs';
import { authorOnly,independent } from './collection.mjs';
export async function createTarget(s,b){fields(b,['name','baselineReportId','scopes','reductionPercent','targetDate','ownerId','scope2Basis']);const report=await s.get('u_reports',uuid(b.baselineReportId));if(report.status!=='APPROVED')fail(422,'APPROVED_BASELINE','Use an approved, frozen baseline report.');
  if(!Array.isArray(b.scopes)||!b.scopes.length||b.scopes.length>3||new Set(b.scopes).size!==b.scopes.length)fail(422,'TARGET_SCOPES','Select one or more unique primary scopes.');b.scopes.forEach(x=>choice(x,['SCOPE_1','SCOPE_2','SCOPE_3'],'scope'));
  const basis=choice(b.scope2Basis||'LOCATION',['LOCATION','MARKET'],'scope2Basis');if(basis==='MARKET'&&!b.scopes.includes('SCOPE_2'))fail(422,'TARGET_BASIS','Market basis requires Scope 2 in target scopes.');const baseline=selectedInventoryTotal(report.snapshot,b.scopes,basis);if(scaled(baseline)<=0n)fail(422,'EMPTY_BASELINE','A target requires a positive recorded baseline.');const reduction=decimal(b.reductionPercent,'reductionPercent',4);if(scaled(reduction,4)>1000000n)fail(422,'PERCENT_RANGE','Reduction percentage must be at most 100.');const target=day(b.targetDate);if(target<=report.snapshot.period.end_date)fail(422,'TARGET_DATE','Target date must follow the baseline period.');await s.userRef(uuid(b.ownerId),['ADMIN','ENTRY','REVIEWER']);
  const r=await s.insert('u_targets',{name:text(b.name,'name',200),baseline_report_id:report.id,scope2_basis:basis,scopes:b.scopes,baseline_kg:baseline,reduction_percent:reduction,target_date:target,owner_id:b.ownerId,created_by:s.user.id});await s.audit('U_TARGET_CREATED',r.id,{baselineReportId:report.id,baselineKg:baseline});return r;}
export async function targetProgress(s,rid,currentReportId){const target=await s.get('u_targets',uuid(rid)),base=await s.get('u_reports',target.baseline_report_id),current=await s.get('u_reports',uuid(currentReportId));if(current.status!=='APPROVED')fail(422,'APPROVED_COMPARISON','Use an approved comparison report.');
  const b=base.snapshot,c=current.snapshot;const relevant=x=>x.inventoryRows.filter(r=>target.scopes.includes(r.scope));const campusSet=x=>[...new Set(relevant(x).map(r=>r.campus_id))].sort().join(',');const duration=x=>(Date.parse(x.period.end_date)-Date.parse(x.period.start_date))/86400000+1;
  const comparable=base.id!==current.id&&b.boundaryStatement===c.boundaryStatement&&campusSet(b)===campusSet(c)&&Math.abs(duration(b)-duration(c))<=2&&c.period.start_date>b.period.end_date;
  const currentKg=selectedInventoryTotal(c,target.scopes,target.scope2_basis||'LOCATION'),delta=format(scaled(target.baseline_kg)-scaled(currentKg));const threshold=format((scaled(target.baseline_kg)*(1000000n-scaled(target.reduction_percent,4))+500000n)/1000000n);
  return {target,currentReportId:current.id,comparisonKgCo2e:currentKg,targetThresholdKgCo2e:threshold,comparable,observedChangeKgCo2e:comparable?delta:null,observedReductionPercent:comparable?percentOf(delta,target.baseline_kg):null,recordedThresholdMet:comparable?scaled(currentKg)<=scaled(threshold):null,
    caution:'Recorded inventory change is not verified project attribution, avoided emissions or a net-zero claim. Review factor, boundary and activity changes. Different declarations, campuses, overlapping periods or substantially different durations are not automatically comparable.'};}
export async function createInitiative(s,b){fields(b,['targetId','campusId','name','ownerId','startDate','endDate','estimatedReductionKg','investmentInr','annualSavingsInr','assumptions']);await s.get('u_targets',uuid(b.targetId));await s.location(uuid(b.campusId));await s.userRef(uuid(b.ownerId),['ADMIN','ENTRY','REVIEWER']);const start=day(b.startDate),end=day(b.endDate);if(start>end)fail(422,'DATE_RANGE','End date must follow start date.');const r=await s.insert('u_initiatives',{target_id:b.targetId,campus_id:b.campusId,name:text(b.name,'name',200),owner_id:b.ownerId,start_date:start,end_date:end,estimated_reduction_kg:decimal(b.estimatedReductionKg,'estimatedReductionKg',6,true),investment_inr:decimal(b.investmentInr,'investmentInr',2,true),annual_savings_inr:decimal(b.annualSavingsInr,'annualSavingsInr',2,true),assumptions:reason(b.assumptions),created_by:s.user.id});await s.audit('U_INITIATIVE_CREATED',r.id);return {...r,inventoryDeduction:false};}
export async function initiativeAction(s,rid,b){fields(b,['version','status','progress','reason']);const old=await s.get('u_initiatives',uuid(rid),{lock:true});version(old,b.version);if(s.user.role!=='ADMIN'&&old.owner_id!==s.user.id)fail(403,'OWNER_REQUIRED','Only the initiative owner or an administrator may update it.');const state=choice(b.status,['PLANNED','IN_PROGRESS','ON_HOLD','COMPLETED'],'status'),progress=integer(b.progress,0,100,'progress');if((state==='COMPLETED')!==(progress===100))fail(422,'PROGRESS_STATE','Only COMPLETED initiatives may have 100% progress, and completed initiatives require 100%.');if(state==='PLANNED'&&progress!==0)fail(422,'PROGRESS_STATE','A planned initiative starts at 0%.');const r=await s.update('u_initiatives',old.id,{status:state,progress});await s.audit('U_INITIATIVE_UPDATED',r.id,{before:old.status,after:state,progress,reason:reason(b.reason)});return {...r,inventoryDeduction:false};}
export async function pcfPreview(s,b){const study=pcfInput(b),factors=[];for(const fid of [...new Set(study.bom.map(l=>l.factorId))])factors.push(await s.get('u_factors',fid));return calculatePcf(study,factors);}
export async function createPcf(s,b){const study=pcfInput(b);await pcfPreview(s,b);const r=await s.insert('u_pcf_studies',{...study,created_by:s.user.id});await s.audit('U_PCF_DRAFTED',r.id,{inventoryIncluded:false});return r;}
export async function pcfAction(s,rid,action,b){fields(b,['version','reason']);const r=await s.get('u_pcf_studies',uuid(rid),{lock:true});version(r,b.version);
  if(action==='submit'){authorOnly(s.user,r);if(r.status!=='DRAFT')fail(409,'INVALID_STATE','Only a draft can be submitted.');const out=await s.update('u_pcf_studies',r.id,{status:'SUBMITTED'});await s.audit('U_PCF_SUBMITTED',r.id);return out;}
  independent(s.user,r);if(r.status!=='SUBMITTED')fail(409,'INVALID_STATE','PCF study is not pending review.');
  if(action==='reject'){const out=await s.update('u_pcf_studies',r.id,{status:'REJECTED',rejection_reason:reason(b.reason)});await s.audit('U_PCF_REJECTED',r.id,{reason:out.rejection_reason});return out;}
  if(action!=='approve')fail(404,'NOT_FOUND','Unknown PCF action.');const factors=[];for(const fid of [...new Set(r.bom.map(l=>l.factorId))])factors.push(await s.get('u_factors',fid));const result=calculatePcf(r,factors),out=await s.update('u_pcf_studies',r.id,{status:'APPROVED',approved_by:s.user.id,result});await s.audit('U_PCF_APPROVED',r.id,{totalKgCo2e:result.totalKgCo2e,inventoryIncluded:false});return out;}
