import { snapshot as scope12Snapshot } from './carbon/reporting.mjs';
import { version } from '../core.mjs';
import { fields,text,uuid,choice,reason,sum,scaled,format,ratio,percentOf,canonical,hash,csvWrite,htmlEscape,SCOPE3_CATEGORIES,fail } from './core.mjs';
import { independent } from './collection.mjs';
export function inventorySummary(rows){const scopeTotals={SCOPE_1:'0.000000',SCOPE_2:'0.000000',SCOPE_3:'0.000000',SUPPLEMENTAL:'0.000000'},categories=new Map(),campuses=new Map();let records=0,evidence=0,supplementalRecords=0;
  for(const r of rows){if(!Object.hasOwn(scopeTotals,r.scope))throw Error('Unknown scope in inventory');scopeTotals[r.scope]=sum([scopeTotals[r.scope],r.kg_co2e]);const n=r.records??1,e=r.evidence_records??(r.evidence_count>0?1:0);
    if(r.scope==='SUPPLEMENTAL'){supplementalRecords+=n;continue;}records+=n;evidence+=e;const key=r.scope+':'+r.category,c=categories.get(key)||{scope:r.scope,category:r.category,kgCo2e:'0.000000',records:0};c.kgCo2e=sum([c.kgCo2e,r.kg_co2e]);c.records+=n;categories.set(key,c);
    const campus=campuses.get(r.campus_id)||{campusId:r.campus_id,kgCo2e:'0.000000',records:0};campus.kgCo2e=sum([campus.kgCo2e,r.kg_co2e]);campus.records+=n;campuses.set(r.campus_id,campus);}
  const total=sum([scopeTotals.SCOPE_1,scopeTotals.SCOPE_2,scopeTotals.SCOPE_3]);const compare=(a,b)=>scaled(a.kgCo2e)>scaled(b.kgCo2e)?-1:scaled(a.kgCo2e)<scaled(b.kgCo2e)?1:0;
  return {totalKgCo2e:total,totalTonnesCo2e:ratio(total,'1000'),scopes:scopeTotals,recordCount:records,supplementalRecordCount:supplementalRecords,evidenceRecordCount:evidence,evidenceCoveragePercent:records?percentOf(String(evidence),String(records)):null,categories:[...categories.values()].sort(compare),campuses:[...campuses.values()].sort(compare),
    boundary:'Primary = calculated Scope 1 + 2 + 3 records. Supplemental student travel is shown separately. PCF and initiative estimates are excluded.',evidenceCoverageDefinition:'Percentage of calculated primary records with evidence, not percentage of emissions independently assured.',completeInventoryClaim:false};}
export function metricSummary(rows){const byTask=new Map();for(const row of rows){const old=byTask.get(row.task_id);if(!old||old.revision<row.revision)byTask.set(row.task_id,row);}const latest=new Map(),selected=[];
  for(const r of byTask.values()){if(r.aggregation==='SUM'){selected.push(r);continue;}const key=[r.campus_id,r.kpi_id,r.bucket].join(':');const old=latest.get(key);if(!old||old.interval_end<r.interval_end||(old.interval_end===r.interval_end&&old.revision<r.revision))latest.set(key,r);}
  selected.push(...latest.values());const metrics=new Map();for(const r of selected){const key=r.kpi_code;let m=metrics.get(key);if(!m){m={code:key,unit:r.unit,aggregation:r.aggregation,value:'0.000000',byCampus:[],sourceSnapshotIds:[],evidenceCount:0};metrics.set(key,m);}if(m.unit!==r.unit)throw Error('KPI unit invariant');
    m.sourceSnapshotIds.push(r.id);m.evidenceCount+=(r.evidence||[]).length;
    if(r.unit==='percent'){m.value=null;m.byCampus.push({campusId:r.campus_id,bucket:r.bucket,value:r.value});m.note='Percentages are separate observations; a weighted total requires explicit denominators.';continue;}
    m.value=sum([m.value,r.value]);let c=m.byCampus.find(c=>c.campusId===r.campus_id);if(!c){c={campusId:r.campus_id,value:'0.000000'};m.byCampus.push(c);}c.value=sum([c.value,r.value]);}
  return [...metrics.values()].sort((a,b)=>a.code.localeCompare(b.code));}
export function coverage(screenings,inventory){const byNum=new Map(screenings.map(s=>[s.category_number,s]));return SCOPE3_CATEGORIES.map((name,i)=>{const s=byNum.get(i+1),records=inventory.filter(r=>r.scope3_category===i+1);return {number:i+1,name,decision:s?.decision||'NOT_ASSESSED',rationale:s?.rationale||null,recordCount:records.length,kgCo2e:sum(records.map(r=>r.kg_co2e)),warning:s?.decision==='INCLUDED'&&!records.length?'Included category has no calculated records.':null};});}
export function intensities(summary,metrics){const campuses=summary.campuses.map(c=>c.campusId);return ['STUDENT_FTE','STAFF_FTE','FLOOR_AREA_M2'].map(code=>{const metric=metrics.find(m=>m.code===code),missing=campuses.filter(id=>!metric?.byCampus.some(c=>c.campusId===id&&scaled(c.value)>0n));const denominator=metric?sum(metric.byCampus.filter(c=>campuses.includes(c.campusId)).map(c=>c.value)):'0.000000';return {denominatorCode:code,denominator,missingCampusIds:missing,kgCo2ePerUnit:campuses.length&&!missing.length?ratio(summary.totalKgCo2e,denominator):null,note:'Uses approved annual normalization values for campuses with calculated primary emissions. Missing or zero denominators produce null, never zero.'};});}
export async function overview(s,periodId){const p=await s.period(uuid(periodId),false),groups=await s.inventoryTotals(p.id),summary=inventorySummary(groups),metrics=metricSummary(await s.metricRows(p.id)),missing=await s.missingTasks(p.id),taskCount=await s.count('u_tasks',{period_id:p.id});
  const openCount=await s.count('u_tasks',{period_id:p.id,status:'OPEN'}),waived=await s.count('u_tasks',{period_id:p.id,status:'WAIVED'}),complete=await s.count('u_tasks',{period_id:p.id,status:'COMPLETE'});
  return {asOf:new Date().toISOString(),period:p,inventory:summary,metrics,intensities:intensities(summary,metrics),collection:{total:taskCount,open:openCount,complete,waived,completionPercent:taskCount?percentOf(String(complete),String(taskCount)):null},missingTasks:missing.slice(0,100),missingTasksTruncated:missing.length>100,
    engine:'DETERMINISTIC_DATABASE_AGGREGATION',notes:['No measured data or emission factors are preloaded.','Values are internally reviewed, not independently assured.','KPI measurements and carbon records are separate ledgers; collection does not automatically post emissions.']};}
export async function snapshotData(s,periodId,boundaryStatement){const period=await s.period(uuid(periodId),false),inventory=await s.inventory(period.id),metricRows=await s.metricRows(period.id),metrics=metricSummary(metricRows),summary=inventorySummary(inventory),screenings=await s.rows('u_scope3_screenings',{period_id:period.id},15),tasks=await s.rows('u_tasks',{period_id:period.id},5000),tenant=await s.get('tenants',s.tenant);
  const supplierPending=await s.count('u_supplier_requests',{period_id:period.id,status:['DRAFT','OPEN','SUBMITTED','REJECTED']});
  const scope12=await scope12Snapshot(s,period.id);
  const data={scope12,schemaVersion:'university-report-2',asOf:new Date().toISOString(),university:{id:tenant.id,name:tenant.name},period,boundaryStatement,inventorySummary:summary,inventoryRows:inventory,metricSummary:metrics,metricSnapshots:metricRows,intensities:intensities(summary,metrics),scope3Coverage:coverage(screenings,inventory),collection:{total:tasks.length,complete:tasks.filter(t=>t.status==='COMPLETE').length,waivers:tasks.filter(t=>t.status==='WAIVED').map(t=>({taskId:t.id,reason:t.waiver_reason})),open:tasks.filter(t=>t.status==='OPEN').length},pendingSupplierRequests:supplierPending,
    assurance:'INTERNAL_REVIEW_ONLY',frameworkStatus:'No automatic BRSR, CSRD, STARS, GRI, ISO or other compliance certification.',limitations:['This report reflects registered activities and the declared boundary, not a guarantee of inventory completeness.','Supplemental student travel is separate from Scope 3.','Enhanced Scope 2 alternatives are included only when the period uses the new source ledger; legacy periods remain unchanged. Offsets, avoided emissions and full LCAs are not implemented.','Core ledger data quality is not retrospectively verified by this extension.']};
  return JSON.parse(JSON.stringify(data));}
export async function createReport(s,b){fields(b,['periodId','title','purpose','boundaryStatement']);const p=await s.period(uuid(b.periodId),false);if(p.status!=='LOCKED')fail(409,'PERIOD_MUST_BE_LOCKED','Resolve pending entries and lock the period before taking a report snapshot.');const snap=await snapshotData(s,p.id,reason(b.boundaryStatement));
  if(snap.scope12?.active&&!snap.scope12.readiness.ready)fail(409,'SCOPE12_NOT_READY','Resolve Scope 1/2 source gaps, pending entries and critical findings before freezing a report.',{blockers:snap.scope12.readiness.blockers});
  const pendingCore=await s.count('activities',{period_id:p.id,status:['DRAFT','SUBMITTED','UNDER_REVIEW','VERIFIED']}),pendingUniversity=await s.count('u_emissions',{period_id:p.id,status:['DRAFT','SUBMITTED']});
  if(pendingCore+pendingUniversity)fail(409,'PENDING_INVENTORY','Complete or explicitly reject pending carbon entries before freezing the final report.');
  if(snap.collection.open)fail(409,'PENDING_TASKS','Resolve every open collection task before generating a final snapshot.');
  const snapshotHash=hash(canonical(snap));const r=await s.insert('u_reports',{period_id:p.id,title:text(b.title,'title',200),purpose:choice(b.purpose,['INVENTORY_EVIDENCE','UNIVERSITY_SUSTAINABILITY','INTERNAL_ESG'],'purpose'),period_version:p.version,snapshot:snap,snapshot_hash:snapshotHash,created_by:s.user.id});await s.audit('U_REPORT_SNAPSHOT_CREATED',r.id,{snapshotHash,periodVersion:p.version});return r;}
export async function reviewReport(s,rid,action,b){fields(b,['version','reason']);const seen=await s.get('u_reports',uuid(rid)),p=await s.period(seen.period_id,false),r=await s.get('u_reports',seen.id,{lock:true});version(r,b.version);independent(s.user,r);if(r.status!=='SUBMITTED')fail(409,'INVALID_STATE','Report is not pending review.');
  if(action==='approve'){if(p.status!=='LOCKED'||p.version!==r.period_version)fail(409,'STALE_REPORT','Period was reopened or changed. Generate a new snapshot before approval.');if(hash(canonical(r.snapshot))!==r.snapshot_hash)fail(409,'INTEGRITY_ERROR','Snapshot hash does not match.');const out=await s.update('u_reports',r.id,{status:'APPROVED',approved_by:s.user.id});await s.audit('U_REPORT_APPROVED',r.id,{snapshotHash:r.snapshot_hash});return out;}
  if(action==='reject'){const out=await s.update('u_reports',r.id,{status:'REJECTED',rejection_reason:reason(b.reason)});await s.audit('U_REPORT_REJECTED',r.id,{reason:out.rejection_reason});return out;}fail(404,'NOT_FOUND','Unknown report action.');}
export async function getReport(s,rid){const r=await s.get('u_reports',uuid(rid)),p=await s.period(r.period_id,false);return {...r,integrityVerified:hash(canonical(r.snapshot))===r.snapshot_hash,currentPeriodVersion:p.version,currentPeriodLocked:p.status==='LOCKED',supersededByPeriodChange:p.version!==r.period_version};}
export async function exportReport(s,rid,formatName){const r=await getReport(s,rid);if(r.status!=='APPROVED')fail(409,'APPROVAL_REQUIRED','Approve the report before exporting it.');if(!r.integrityVerified)fail(409,'INTEGRITY_ERROR','Snapshot hash does not match.');choice(formatName,['json','csv','html'],'format');const name='CarbonSynq-University-'+r.id;
  if(formatName==='json')return {name:name+'.json',mime:'application/json; charset=utf-8',bytes:JSON.stringify(r,null,2)};
  const columns=['ledger','record_id','activity_date','campus_id','category','scope','scope3_category','quantity','unit','kg_co2e','evidence_count'];
  if(formatName==='csv'){
    // Keep the legacy columns stable. Enhanced alternatives are additional columns,
    // never additional inventory rows or additions to primary kg_co2e.
    const extra=r.snapshot.scope12?.active?['scope1_kg','scope2_location_kg','scope2_market_kg','biogenic_co2_kg']:[];
    const calculations=new Map((r.snapshot.scope12?.calculationRows||[]).map(c=>[c.record_id,c]));
    const values=r.snapshot.inventoryRows.map(row=>{const c=row.ledger==='CARBON_SCOPE12'?calculations.get(row.record_id):null;
      return [...columns.map(k=>row[k]),...(extra.length?[c?.scope1_kg,c?.location_kg,c?.market_kg,c?.biogenic_kg]:[])];});
    return {name:name+'.csv',mime:'text/csv; charset=utf-8',bytes:csvWrite([...columns,...extra],values)};
  }
  const esc=htmlEscape,snap=r.snapshot,table=(headers,rows)=>'<table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(cell=>'<td>'+esc(cell)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
  const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(r.title)+'</title><style>body{font:15px/1.6 system-ui,sans-serif;max-width:1120px;margin:36px auto;padding:0 24px;color:#1c2e28}h1{font-size:34px}h2{margin-top:36px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border-bottom:1px solid #dce2df;padding:9px;text-align:left;overflow-wrap:anywhere}th{background:#eef5f0}.flag{padding:12px;background:#fff2cf}code{overflow-wrap:anywhere}footer{font-size:12px;margin-top:36px}@media print{body{margin:0}thead{display:table-header-group}tr{break-inside:avoid}}</style><body><p>CarbonSynq / UNIVERSITY SUSTAINABILITY</p><h1>'+esc(r.title)+'</h1><p>'+esc(snap.university.name)+' | '+esc(snap.period.name)+'</p><p class="flag">Internally approved snapshot. No compliance certification or independent assurance is asserted.'+(r.supersededByPeriodChange?' The underlying period has since changed.':'')+'</p><h2>Inventory</h2><p><strong>'+esc(snap.inventorySummary.totalTonnesCo2e)+' tCO2e</strong> recorded primary inventory. Supplemental student travel: '+esc(snap.inventorySummary.scopes.SUPPLEMENTAL)+' kgCO2e, excluded from the primary total.</p><p>'+esc(snap.boundaryStatement)+'</p>'+table(['Scope','kgCO2e'],Object.entries(snap.inventorySummary.scopes))+(snap.scope12?.active?'<h2>Scope 1 / Scope 2 alternative methods</h2>'+table(['Measure','kg'],[['Scope 1',snap.scope12.summary.scope1.kgCo2e],['Scope 2 location-based',snap.scope12.summary.scope2.locationKgCo2e],['Scope 2 market-based (alternative)',snap.scope12.summary.scope2.marketKgCo2e??'Not asserted'],['Biogenic CO2 (separate)',snap.scope12.summary.scope1.biogenicCo2Kg]])+'<p>Location and market results must not be added together. Gas details and source coverage are in the frozen JSON snapshot.</p>':'')+'<h2>University indicators</h2>'+table(['Indicator','Value','Unit'],snap.metricSummary.map(m=>[m.code,m.value??'See individual observations',m.unit]))+'<h2>Scope 3 coverage</h2>'+table(['Category','Decision','Records','Rationale'],snap.scope3Coverage.map(c=>[c.number+'. '+c.name,c.decision,c.recordCount,c.rationale||'Not assessed']))+'<h2>Calculated ledger</h2>'+table(columns,snap.inventoryRows.map(row=>columns.map(c=>row[c])))+'<footer><p>Snapshot SHA-256: <code>'+esc(r.snapshot_hash)+'</code></p><p>Data as of '+esc(snap.asOf)+'. Evidence hashes and factor provenance are included in the JSON export.</p><p>'+snap.limitations.map(esc).join(' ')+'</p></footer></body></html>';
  return {name:name+'.html',mime:'text/html; charset=utf-8',bytes:html};}
export const INSIGHTS=['EMISSIONS_SUMMARY','MISSING_SUBMISSIONS','TOP_HOTSPOTS','EVIDENCE_GAPS','SCOPE3_COVERAGE'];
export async function insights(s,b){fields(b,['periodId','questionId']);choice(b.questionId,INSIGHTS,'questionId');const pid=uuid(b.periodId);await s.period(pid,false);let facts,citations=[];
  if(b.questionId==='MISSING_SUBMISSIONS'){const rows=await s.missingTasks(pid);facts={openTasks:await s.count('u_tasks',{period_id:pid,status:'OPEN'}),tasks:rows.slice(0,100),truncated:rows.length>100};citations=rows.slice(0,100).map(r=>({type:'task',id:r.id,path:`/api/v2/university/tasks/${r.id}`}));}
  else {const rows=await s.inventory(pid),summary=inventorySummary(rows);citations=rows.map(r=>({type:'calculation',id:r.id,recordId:r.record_id,path:r.ledger==='CORE'?`/api/v2/activities/${r.record_id}`:r.ledger==='CARBON_SCOPE12'?`/api/v2/university/carbon/records/${r.record_id}`:`/api/v2/university/emissions/${r.record_id}`}));
    if(b.questionId==='EMISSIONS_SUMMARY')facts=summary;
    if(b.questionId==='TOP_HOTSPOTS')facts={categories:summary.categories.slice(0,10),definition:'Largest recorded emission categories, not a recommendation or verified reduction potential.'};
    if(b.questionId==='EVIDENCE_GAPS')facts={recordsWithoutEvidence:rows.filter(r=>r.evidence_count===0).map(r=>({id:r.record_id,scope:r.scope,category:r.category,ledger:r.ledger})),note:'Absence of a linked document is not proof that the record is false.'};
    if(b.questionId==='SCOPE3_COVERAGE')facts=coverage(await s.rows('u_scope3_screenings',{period_id:pid},15),rows);}
  return {questionId:b.questionId,periodId:pid,asOf:new Date().toISOString(),engine:'DETERMINISTIC_SQL_NOT_LLM',facts,citations,generatedNarrative:false,note:'These are traceable database facts. No free-form SQL, external AI model, OCR claim or autonomous action is used.'};}
