import test from 'node:test';import assert from 'node:assert/strict';
import * as c from '../../src/university/carbon/core.mjs';
import {SOURCE_KINDS,EXTRA_KPIS,QUALITY_CRITERIA} from '../../src/university/carbon/catalog.mjs';
import {fixture,sourceBody,factorBody,instrumentBody,note} from './memory.mjs';
const throws=(fn,code)=>assert.throws(fn,e=>e.code===code);
const stock={mode:'FUEL_STOCK',unit:'litre',opening:'100',received:'250',transfersIn:'20',closing:'80',transfersOut:'10'};
test('fuel stock consumes 280 litres, not total purchases',()=>assert.equal(c.quantityPreview(stock).quantity,'280.000000'));
test('negative stock is rejected rather than clamped',()=>throws(()=>c.quantityPreview({...stock,closing:'900'}),'NEGATIVE_BALANCE'));
test('fuel balance refuses currency',()=>throws(()=>c.quantityPreview({...stock,unit:'INR'}),'INVALID_CHOICE'));
test('meter uses multiplier',()=>assert.equal(c.quantityPreview({mode:'METER',unit:'kWh',opening:'1200',closing:'1250',multiplier:'20'}).quantity,'1000.000000'));
test('single documented rollover uses exclusive maximum',()=>assert.equal(c.quantityPreview({mode:'METER',unit:'kWh',opening:'990',closing:'5',multiplier:'1',rolloverAt:'1000'}).quantity,'15.000000'));
test('negative meter without rollover refuses reset',()=>throws(()=>c.quantityPreview({mode:'METER',unit:'kWh',opening:'990',closing:'5',multiplier:'1'}),'METER_RESET'));
test('rollover cannot be fabricated on positive movement',()=>throws(()=>c.quantityPreview({mode:'METER',unit:'kWh',opening:'2',closing:'5',multiplier:'1',rolloverAt:'1000'}),'METER_ROLLOVER'));
test('refrigerant balance excludes recovered closing stock and transferred gas',()=>assert.equal(c.quantityPreview({mode:'REFRIGERANT_BALANCE',openingEquipmentKg:'100',openingStockKg:'10',acquiredKg:'5',closingEquipmentKg:'95',closingStockKg:'8',transferredOutKg:'2'}).quantity,'10.000000'));
test('refrigerant purchases do not qualify as leak-only topup',()=>throws(()=>c.quantityPreview({mode:'SERVICE_TOPUP',lossReplacementKg:'5',replacesLeakOnly:false,notes:note}),'LEAK_ATTESTATION'));
test('documented topup permits loss replacement',()=>assert.equal(c.quantityPreview({mode:'SERVICE_TOPUP',lossReplacementKg:'5',replacesLeakOnly:true,notes:note}).quantity,'5.000000'));
for(const [unit,q,result] of [['MWh','1.2','1200.000000'],['GJ','3.6','1000.000000'],['GJ','1','277.777778'],['kWh','12','12.000000']])test('exact delivered-energy conversion '+unit+' '+q,()=>assert.equal(c.quantityPreview({mode:'ENERGY_CONVERSION',quantity:q,unit}).quantity,result));
test('electricity exports do not subtract gross imports',()=>{const r=c.quantityPreview({mode:'ELECTRICITY_BALANCE',grossImportsKwh:'100',onsiteGenerationKwh:'40',exportsKwh:'10'});assert.equal(r.quantity,'100.000000');assert.equal(r.campusUseKwh,'130.000000');});
test('negative campus balance must be reconciled',()=>throws(()=>c.quantityPreview({mode:'ELECTRICITY_BALANCE',grossImportsKwh:'1',onsiteGenerationKwh:'1',exportsKwh:'5'}),'NEGATIVE_BALANCE'));
test('factor gas breakdown computes CO2 CH4 N2O exactly',()=>{const f=c.factorInput(factorBody({components:[{gas:'CO2',massPerUnit:'2',gwp:'1'},{gas:'CH4',massPerUnit:'0.01',gwp:'28'},{gas:'N2O',massPerUnit:'0.001',gwp:'265'}]}));const r=c.calculateGas('100',f);assert.equal(r.kgCo2e,'254.500000');assert.equal(r.gases.length,3);assert.equal(r.gasBreakdownAvailable,true);});
test('biogenic CO2 separate but CH4 and N2O remain in inventory',()=>{const r=c.calculateGas('100',c.factorInput(factorBody({components:[{gas:'CO2_BIOGENIC',massPerUnit:'2',gwp:'1'},{gas:'CH4',massPerUnit:'0.01',gwp:'28'},{gas:'N2O',massPerUnit:'0.001',gwp:'265'}]})));assert.equal(r.kgCo2e,'54.500000');assert.equal(r.biogenicCo2Kg,'200.000000');});
test('aggregate CO2e cannot have extra gases added',()=>throws(()=>c.factorInput(factorBody({components:[{gas:'CO2E',massPerUnit:'2.68',gwp:'1'},{gas:'CH4',massPerUnit:'0.01',gwp:'28'}]})),'DOUBLE_FACTOR'));
test('combustion CO2 alone is not presented as all gases',()=>throws(()=>c.factorInput(factorBody({components:[{gas:'CO2',massPerUnit:'2.68',gwp:'1'}]})),'COMBUSTION_GAS_COVERAGE'));
test('named refrigerant GWP is supplied explicitly',()=>{const f=c.factorInput(factorBody({kind:'REFRIGERANT',substance:'R_TEST',unit:'kg',components:[{gas:'R_TEST',massPerUnit:'1',gwp:'100'}]}));assert.equal(c.calculateGas('2',f).kgCo2e,'200.000000');});
test('refrigerant factor must match gas name and unit mass',()=>throws(()=>c.factorInput(factorBody({kind:'REFRIGERANT',substance:'R_TEST',unit:'kg',components:[{gas:'CO2E',massPerUnit:'100',gwp:'1'}]})),'GAS_FACTOR'));
test('Scope2 CO2-only factor must instead be documented CO2e',()=>throws(()=>c.factorInput(factorBody({kind:'PURCHASED_HEAT',substance:'HEAT',unit:'kWh',use:'LOCATION',components:[{gas:'CO2',massPerUnit:'0.2',gwp:'1'}]})),'ENERGY_FACTOR'));
test('zero factor requires explanation',()=>assert.throws(()=>c.factorInput(factorBody({components:[{gas:'CO2E',massPerUnit:'0',gwp:'1'}]}))));
test('precision survives quantities beyond float safe integer',()=>assert.equal(c.calculateGas('999999999999.123456',c.factorInput(factorBody({components:[{gas:'CO2E',massPerUnit:'0.123456789',gwp:'1'}]}))).kgCo2e,'123456788999.891785'));
test('market allocation computes remaining consumption with residual',()=>{const zero=c.factorInput(factorBody({components:[{gas:'CO2E',massPerUnit:'0',gwp:'1'}],zeroReason:note})),res=c.factorInput(factorBody({components:[{gas:'CO2E',massPerUnit:'0.9',gwp:'1'}]}));assert.equal(c.calculateMarket('100',[{quantityKwh:'40',factor:zero}],res).kgCo2e,'54.000000');});
test('unmatched market quantity cannot be silently zero',()=>throws(()=>c.calculateMarket('100',[],null),'UNCOVERED_MARKET_LOAD'));
test('market over-allocation rejected',()=>assert.throws(()=>c.calculateMarket('1',[{quantityKwh:'2',factor:c.factorInput(factorBody())}],null)));
test('location commodity cannot be arbitrary',()=>throws(()=>c.sourceInput(sourceBody(fixture(),{kind:'PURCHASED_ELECTRICITY',substance:'DIESEL',unit:'kWh'})),'COMMODITY_MISMATCH'));
test('all source kinds declare scope and unit',()=>{assert.equal(Object.keys(SOURCE_KINDS).length,10);for(const x of Object.values(SOURCE_KINDS))assert.ok(x.scope&&x.units.length);});
test('ten supplementary definitions are distinct and non-emissions records',()=>{assert.equal(EXTRA_KPIS.length,10);assert.equal(new Set(EXTRA_KPIS.map(k=>k.code)).size,10);});
test('instrument requires quality checks rather than checkbox-only claim',()=>{const f=fixture();const b=instrumentBody(f,f.actors.ADMIN.id);delete b.qualityChecks[QUALITY_CRITERIA[0]];assert.throws(()=>c.instrumentInput(b));});
test('instrument cannot claim a future retirement',()=>throws(()=>c.instrumentInput(instrumentBody(fixture(),fixture().actors.ADMIN.id,{retiredOn:'2099-01-01'})),'FUTURE_RETIREMENT'));
test('same serial normalized independent of whitespace and case',()=>{const f=fixture(),a=c.instrumentInput(instrumentBody(f,f.actors.ADMIN.id,{registry:'Registry',serial:'abc 123'})),b=c.instrumentInput(instrumentBody(f,f.actors.ADMIN.id,{registry:'REGISTRY',serial:'ABC123'}));assert.equal(a.serial_key,b.serial_key);});
test('coverage reports leading and trailing missing days',()=>assert.deepEqual(c.gaps('2026-01-01','2026-01-31',[{interval_start:'2026-01-10',interval_end:'2026-01-20'}]),[{from:'2026-01-01',to:'2026-01-09'},{from:'2026-01-21',to:'2026-01-31'}]));
test('adjacent periods give no missing dates',()=>assert.deepEqual(c.gaps('2026-01-01','2026-01-31',[{interval_start:'2026-01-01',interval_end:'2026-01-15'},{interval_start:'2026-01-16',interval_end:'2026-01-31'}]),[]));
