/** Test double: does NOT execute SQL, RLS, distributed locks or real object storage. */
import {MemoryStore,fixture as baseFixture} from '../university/memory-store.mjs';
import {id} from '../../src/core.mjs';
import {sum} from '../../src/university/core.mjs';
import {CHECKLIST,QUALITY_CRITERIA} from '../../src/university/carbon/catalog.mjs';
import * as svc from '../../src/university/carbon/service.mjs';
export class CarbonMemory extends MemoryStore {
 for(u){return new CarbonMemory(this.state,u);}
 async insert(t,d){this.state.tables[t]||=[];return super.insert(t,d);}
 async carbonAllocationUsed(i){const allocations=await this.rows('u_c_allocations',{instrument_id:i},5000),live=await this.carbonActiveAll();return sum(allocations.filter(a=>live.some(r=>r.record_id===a.record_id)).map(a=>a.quantity_kwh));}
 async carbonActiveAll(){const records=await this.rows('u_c_records',{status:'CALCULATED'},5000),out=[];for(const r of records){if(await this.count('u_c_voids',{record_id:r.id,status:'APPROVED'}))continue;const c=(await this.rows('u_c_calculations',{record_id:r.id},1))[0];if(c)out.push({...r,...c,record_id:r.id,id:c.id,evidence_count:r.evidence_ids.length});}return out;}
 async carbonActive(p){return (await this.carbonActiveAll()).filter(r=>r.period_id===p);}
 async inventory(p){return [...await super.inventory(p),...(await this.carbonActive(p)).map(r=>({...r,kg_co2e:r.scope1_kg??r.location_kg,category:r.kind,scope3_category:null,activity_date:r.interval_end,ledger:'CARBON_SCOPE12'}))];}
}
export function fixture(){const f=baseFixture();f.s=new CarbonMemory(f.state,f.actors.ADMIN);return f;}
export const note='SYNTHETIC TEST ONLY - independently reviewed fixture assumption';
export function sourceBody(f,extra={}){return {campusId:f.campus,ownerId:f.actors.ENTRY.id,code:'SOURCE_'+id().slice(0,8).toUpperCase(),name:'Synthetic boiler',kind:'STATIONARY_COMBUSTION',substance:'DIESEL',unit:'litre',region:'TEST',facilityType:'ACADEMIC',activeFrom:'2026-04-01',activeTo:'2027-03-31',description:note,...extra};}
export function factorBody(extra={}){return {name:'Synthetic all-gas combustion factor',kind:'STATIONARY_COMBUSTION',substance:'DIESEL',unit:'litre',use:'DIRECT',components:[{gas:'CO2E',massPerUnit:'2.68',gwp:'1'}],gwpBasis:note,source:note,sourceUrl:'https://example.invalid/synthetic-factor',region:'TEST',boundary:note,versionLabel:'TEST-'+id(),validFrom:'2026-04-01',validTo:'2027-03-31',...extra};}
export function boundaryBody(f,sources,extra={}){return {periodId:f.period,campusIds:[f.campus],campusExclusions:[],approach:'OPERATIONAL_CONTROL',statement:note,baseYear:2026,recalculationPolicy:note,scope2Mode:'DUAL',scope2Rationale:note,sources:sources.map(s=>({sourceId:s.id,decision:'INCLUDED',rationale:note,frequency:'ANNUAL',evidenceIds:[]})),screening:CHECKLIST.map(c=>({campusId:f.campus,code:c.code,decision:sources.some(s=>s.kind===c.kind||(c.kind==='THERMAL_ENERGY'&&s.kind.startsWith('PURCHASED_')&&s.kind!=='PURCHASED_ELECTRICITY'))?'PRESENT':'NOT_APPLICABLE',rationale:note})),evidenceIds:[f.document.id],...extra};}
export function recordBody(f,source,factor,extra={}){return {periodId:f.period,sourceId:source.id,intervalStart:'2026-04-01',intervalEnd:'2027-03-31',externalKey:'test:'+id(),description:note,quantityInput:{mode:'DIRECT',quantity:'100',unit:source.unit},factorId:factor.id,evidenceIds:[f.document.id],dataQuality:'MEASURED',...extra};}
export async function approvedFactor(f,body=factorBody()){const r=await svc.createFactor(f.s,body);return svc.reviewFactor(f.s.for(f.actors.REVIEWER),r.id,'approve',{version:r.version});}
export async function activate(f,sources,extra={}){const r=await svc.createBoundary(f.s,boundaryBody(f,sources,extra));return svc.reviewBoundary(f.s.for(f.actors.REVIEWER),r.id,'approve',{version:r.version});}
export async function readyFixture(kind='DIRECT'){const f=fixture();f.source=await svc.createSource(f.s,sourceBody(f,kind==='ENERGY'?{kind:'PURCHASED_ELECTRICITY',substance:'ELECTRICITY',unit:'kWh'}:{}));f.factor=await approvedFactor(f,factorBody(kind==='ENERGY'?{kind:'PURCHASED_ELECTRICITY',substance:'ELECTRICITY',unit:'kWh',use:'LOCATION',components:[{gas:'CO2E',massPerUnit:'0.7',gwp:'1'}]}:{}));f.boundary=await activate(f,[f.source]);if(kind==='ENERGY'){f.fallback=await approvedFactor(f,factorBody({kind:'PURCHASED_ELECTRICITY',substance:'ELECTRICITY',unit:'kWh',use:'RESIDUAL',components:[{gas:'CO2E',massPerUnit:'0.9',gwp:'1'}]}));}return f;}
export async function calculate(f,body){const e=f.s.for(f.actors.ENTRY);let r=await svc.createRecord(e,body);r=await svc.recordAction(e,r.id,'submit',{version:r.version});return svc.recordAction(f.s.for(f.actors.REVIEWER),r.id,'approve',{version:r.version});}
export function instrumentBody(f,factorId,extra={}){return {periodId:f.period,name:'Synthetic retired EAC',kind:'EAC',registry:'TEST ONLY',serial:'TEST-'+id(),beneficiary:'Synthetic Test University',region:'TEST',quantityKwh:'40',validFrom:'2026-04-01',validTo:'2027-03-31',vintageFrom:'2026-04-01',vintageTo:'2027-03-31',retiredOn:'2026-04-02',factorId,qualityChecks:Object.fromEntries(QUALITY_CRITERIA.map(k=>[k,{assessment:'PASS',explanation:note}])),evidenceIds:[f.document.id],...extra};}
export async function instrument(f,extra={}){const factor=await approvedFactor(f,factorBody({kind:'PURCHASED_ELECTRICITY',substance:'ELECTRICITY',unit:'kWh',use:'MARKET_CONTRACT',components:[{gas:'CO2E',massPerUnit:'0',gwp:'1'}],zeroReason:note}));let r=await svc.createInstrument(f.s,instrumentBody(f,factor.id,extra));return svc.reviewInstrument(f.s.for(f.actors.REVIEWER),r.id,'approve',{version:r.version});}
